### ISSUE TITLE
Newly introduced region in OCI stipulates usage of newer version of oci-java-sdk client

### ISSUE THREAD

**Issue by dcsdemo** [oracle/oci-java-sdk#101]
There was recently added a new region "ca-toronto-1" in OCI.

Until now we used the OCI client version 1.2.49.
While the data class https://github.com/oracle/oci-java-sdk/blob/bab8f17502f344d3f50165ba951d3d33a1d6315c/bmc-identity/src/main/java/com/oracle/bmc/identity/model/Region.java#L28 was able to accommodate the new region "ca-toronto-1"  (as it is a simple wrapper for returned JSON) the API that requires the region to be specified as a parameter, e. g.:
https://github.com/oracle/oci-java-sdk/blob/bab8f17502f344d3f50165ba951d3d33a1d6315c/bmc-identity/src/main/java/com/oracle/bmc/identity/IdentityClient.java#L286
https://github.com/oracle/oci-java-sdk/blob/bab8f17502f344d3f50165ba951d3d33a1d6315c/bmc-identity/src/main/java/com/oracle/bmc/identity/IdentityClient.java#L297
depends on existence of the enum value https://github.com/oracle/oci-java-sdk/blob/e53f2b5112e5285fb93a63d76ea8124d18e943c2/bmc-common/src/main/java/com/oracle/bmc/Region.java#L25 . But this enum value was not available for 1.2.49. 

It is really weird that introduction of a new region in OCI requires an update of an OCI client to newer version. 

You can probably imagine that in a corporate environments it is not a simple task to update the used  library version. It may go through a legal approval process and can really take quite long time (or it can be even impossible to upgrade the OCI client). But anyway customers want to use the resources in newly introduced region.

Would it be possible that you introduce also an API that would not be dependent on Region enum, but rather only on String?

Thank you,
Jachym

**Comment by andy-miles** [comment]
With Java SDK version >= 1.2.34, you can instead pass a `regionId` as a string (as you pointed out) and still have it work for new regions in the oraclecloud.com realm.  I recommend this instead of relying on the Regions enum reference.

Example:
```
final AuthenticationDetailsProvider provider =
        new ConfigFileAuthenticationDetailsProvider(configurationFilePath, profile);
final Identity identityClient = IdentityClient.builder()
        .region("ca-toronto-1")
        .build(provider);
final ListRegionsRequest request = istRegionsRequest.builder().build();
final ListRegionsResponse response = identityClient.listRegions(request);

System.out.println(response.getItems());
```

**Comment by andy-miles** [comment]
If the above work-around doesn't work for you, please reopen this issue and let us know.

**Comment by dcsdemo** [comment]
Andy, you are right.
I did not see the catch code that treats situation if the String representation of the region does not fit into region enums. 

https://github.com/oracle/oci-java-sdk/blob/bab8f17502f344d3f50165ba951d3d33a1d6315c/bmc-identity/src/main/java/com/oracle/bmc/identity/IdentityClient.java#L304

Thank you,
Jachym
