### ISSUE TITLE
Expose regionId field in Get Tenancy API to get the home Region of Tenancy

### ISSUE THREAD

**Issue by aunayak** [oracle/oci-java-sdk#105]
Currently getTenancy API returns the getHomeRegionKey which is the Region Code of the Home region, But with latest releases OCI has deprecated the region code in Region Enum, So expose region ID field in getTenancy API so that we can convert back the region ID to Region Name easily.

**Comment by jodoglevy** [comment]
Thanks for the feedback. I'll pass this request along to the Identity team. In the mean time, can't the [List Regions](https://docs.cloud.oracle.com/iaas/api/#/en/identity/20160918/Region/ListRegions) API be used to get the info you need?

**Comment by aunayak** [comment]
Thanks for the advice @jodoglevy , List Region would list the regions in the system but would not help me Identify the Home region of the Tenancy. Since the feature is getting deprecated there must me some mechanism to support Backward compatibility(Dependencies).If Region id is exposed via get Tenancy API then it would be easy to translate the region id to region object using the Region Enum.

**Comment by jodoglevy** [comment]
Sorry, what I meant was using the GetTenancy API to get the 'homeRegionKey', and then calling the ListRegions API, and filtering the results to the region model whose 'key' field matches the 'homeRegionKey' from the GetTenancy response. That region model will contain the region 'name' field you'd need to use.

**Comment by andy-miles** [comment]
Since there has been no further comments since @jodoglevy's provided answer, I'm closing this issue. If you have any further questions/concerns, please re-open it.
