### ISSUE TITLE
Creating Policy immediately after compartment creation fails unexpectedly

### ISSUE THREAD

**Issue by Ahwleung** [oracle/oci-java-sdk#108]
Using OCI Java SDK, it looks like there is a race condition that causes policy creation to fail if run immediately after compartment creation.

Context: We are creating an automated provisioning scenario that creates a compartment, groups, and policies.

A simple repro can be done by creating any policy via CreatePolicyRequest that references a compartment that has been created just before.

Adding as short as a 5s delay will allow subsequent CreatePolicyRequest to run successfully.  However we have no way to programatically get feedback on the accessibility of the compartment.  All we have is lifecycleState (which always shows as "Active") and a constantly null "is-accessible".

Solution would be to either expose compartment availability via the CreateCompartmentResponse or do not return the CreateCompartmentResponse until the compartment has fully been provisioned and can be used without issue.

**Comment by jodoglevy** [comment]
This appears to be an issue with the Identity service, rather than the Java SDK. Let me reach out to the Identity service team and I will ask them to respond to you here.

**Comment by msleeman** [comment]
This is likely due to a race issue between the updates you do for the compartment taking longer than your delay in creating policy that references that new compartment.  I'm checking to see if we have further info, but thank you for the report.

**Comment by msleeman** [comment]
Thanks again for the report I talked in depth with my developers and it will not be possible to fix this with our current architecture.  There is a race conditions between two system and there is not callback/ack channel, currently.   I can't go into more detail, but I hope you get the gist that this would be a very big change .

**Comment by andy-miles** [comment]
Since there has been no further comments on this issue, I'm closing it.  If you have any further questions/concerns, please re-open it.
