### ISSUE TITLE
SDK rejects responses that carry charset utf8 in content-type header

### ISSUE THREAD

**Issue by astromechza** [oracle/oci-java-sdk#110]
We've noticed this when hitting an api endpoint. We get exceptions wrapped in a `Unexpected Content-Type` message because a particular OCI api returns a content type of `application/json;charset=utf-8`.

We see in `ResponseHelper#throwIfNotSuccessful` that it does a simple equals call and doesn't anticipate charset being explicitly defined as utf-8 which is already the assumption.

I'd like to suggest that the media type be compared using the `isCompatible()` field and _if_ the `charset` parameter is set, then it *must* be `utf-8`. This would keep the assumptions the same and allow the api responses to be correctly handled.

I can submit a PR for this.

**Comment by jodoglevy** [comment]
@astromechza we currently have a thread on this going internally already, going to close this
