### ISSUE TITLE
UploadRequest does not callback invocationCallback object when multipart upload is being used

### ISSUE THREAD

**Issue by pcramasamy** [oracle/oci-java-sdk#112]
This issue is very similar to #58.

		File uploadFile = new File("testfile");
		PutObjectRequest putRequest = PutObjectRequest.builder().namespaceName("testnamespace").bucketName("testbucket")
        		.objectName(uploadFile.getName())
        		.invocationCallback(new DateHeaderConsumer()) 
        		.build();
        
		UploadConfiguration uploadConfiguration = UploadConfiguration
				.builder().allowMultipartUploads(true)
				.minimumLengthForMultipartUpload(2)
				.allowParallelUploads(true).build();
		UploadManager uploadManager = new UploadManager(osclient, uploadConfiguration);
		UploadRequest uploadRequest = UploadRequest.builder(uploadFile)
				.allowOverwrite(true).build(putRequest);
		uploadManager.upload(uploadRequest);

Here, the minimum length for multipart upload is set to 2MB. DateHeaderConsumer gets the callback fine when the uploadFile is less than 2MB, but it does not get the callback if the uploadFile is more than 2MB. We use sdk version 1.2.35, but this issue reproduces with latest 1.4.3 as well.

**Comment by andy-miles** [comment]
To better understand your use-case, are you expecting your `DateHeaderConsumer#accept()` to be invoked for all multipart related requests made to the Object Storage? 

For example, if 100 parts is to be uploaded when using multipart upload, would you be expecting an invocation for `CreateMultipartUploadRequest`, 100 * `UploadPartRequest`, and `CommitMultipartUploadRequest`s that would total 102 invocations of the callback?

**Comment by pcramasamy** [comment]
Yes, we are expecting DateHeaderConsumer.accept() gets called for every multipart related request.

**Comment by andy-miles** [comment]
[Release 1.5.0](https://github.com/oracle/oci-java-sdk/releases/tag/v1.5.0) includes the fix for the UploadManager to invoke your `invocationCallback` specified in your `PutObjectRequest` for all multipart related requests when uploading an object using the multipart APIs.

Please update to this version and verify that it invokes your callback for your use-case.  If you continue to experience issues, please reply to this issue.
