### ISSUE TITLE
Cannot overwrite files with PutObjectRequest

### ISSUE THREAD

**Issue by koszta5** [oracle/oci-java-sdk#113]
When pushing the same filename putObjectRequestFails on error (which seems wrong anyway):
`com.oracle.bmc.model.BmcException: (404, BucketNotFound, false) Either the bucket named 'MY_FILE_NAME' does not exist in the namespace 'MY_NAME_SPACE' or you are not authorized to access it (opc-request-id: XYZ)`

It does not allow to overwrite files in cloud:

```
PutObjectRequest request =
				PutObjectRequest.builder()
								.bucketName(bucketSetName)
								.namespaceName(namespaceName)
								.objectName(objectName)
								.contentType(contentType)
								.contentLength(file.length())
								.contentLanguage(contentLanguage)
								.contentEncoding(contentEncoding)
								.opcMeta(metadata)
								.build();

UploadManager.UploadRequest uploadDetails =
				UploadManager.UploadRequest.builder(file).allowOverwrite(true).build(request);
UploadManager.UploadResponse response = manager.upload(uploadDetails);
```

**Comment by jodoglevy** [comment]
@koszta5 - are you sure the bucket to upload to exists in the namespace you referenced in the request? According to the error message above, the bucket to upload to does not exist in that namespace. In addition, from the error text you provided, it looks like you passed the file name as the bucket name -- was that intended? If not, that could possibly be the issue.

From above:
> Either the bucket named 'MY_FILE_NAME' does not exist

**Comment by koszta5** [comment]
@jodoglevy - yes I am sure that the bucket exists. When I upload a file that was not uploaded before it works just fine. And I please see my code - it is exactly copied "as is" from runtime. I specify bucketSet as `bucketSetName`

That is why I am saying that there are in fact 2 issues: 1. overwrite does not work, 2. exception message is wrong/misleading

**Comment by jodoglevy** [comment]
Got it, thanks. Can you provide the opc-request-id of a failing request of this type, so I can route this to the Object Storage team to take a look?

**Comment by koszta5** [comment]
This is a sample request id 
opc-request-id: f0533461-516c-b8cf-07ae-ac4f22f0bc87

**Comment by jodoglevy** [comment]
Thanks, will route this to the Object Storage team.

**Comment by jodoglevy** [comment]
@rsyamkum @srajarao can you take a look?

**Comment by srajarao73** [comment]
@koszta5 can you please verify if you have OBJECT_OVERWRITE permission. to overwrite an object, you need this permission. Note that we precluded OBJECT_OVERWRITE permission to prevent modifications to existing object, along with OBJECT_DELETE. (https://docs.cloud.oracle.com/iaas/Content/Security/Reference/objectstorage_security.htm?Highlight=OBJECT_OVERWRITE)

**Comment by koszta5** [comment]
Hi ,
Ok i actually think this might be the problem but it is totally undocumented. Can you please push some effort in that regard. I will double check the setups tmrw (my working hours are EUR)

**Comment by jodoglevy** [comment]
@koszta5 were you able to resolve the issue per @srajarao73 's solution?

**Comment by koszta5** [comment]
Hi,
getting access for me to our instance has proved to be close to impossible due to limitations due to IT Security. 
So I cant confirm. But either way - the exception is VERY misleading. I am still working on getting the access granted. Can you please change the error message of the exception for now? When the permission is not allowed but your request will use it, it should throw a meaningful error

**Comment by jodoglevy** [comment]
@koszta5  the error message mentions that the issue could be a lack of authorization, isn't that what the issue ended up being?

We purposefully make it ambiguous in our errors as to whether the error was due to not found or not authorized, in order to not expose your resources' existence to people who shouldn't have access to such information.

**Comment by koszta5** [comment]
I think that the given access right missing could be a part of the error and still would not introduce a security hole. 
1. what is more typical/likely scenario - a hacker trying to break it (I believe there are better ways) or user having a hard time around a new (and not small in possibilities) API?
2. If making the exception more specific is not an option I would suggest at least adding some explicit warnings in documentation of this function and its Javadoc. I was clueless

**Comment by koszta5** [comment]
OK :) - API owner (your) call 

Thanks for the effort to update docs. This would be great. I hate not closed issues, so lets close this one and once I get the proper access to double check I will file a new one if the problem persists with correct setup in place.
Thanks

**Comment by jodoglevy** [comment]
Sounds good, thanks @koszta5 !
