### ISSUE TITLE
Getting error The Content-Length header is required while uploading few files to Object Store

### ISSUE THREAD

**Issue by gyanshankar** [oracle/oci-java-sdk#117]
I am using oci-sdk version 1.3.2 to upload a few files to Object Store.
After uploading 2 files successfully the third upload fails with below error 

`com.oracle.bmc.model.BmcException: (411, ContentLengthRequired, false) The Content-Length header is required (opc-request-id:`

I have tried setting contentLength but it still results in same error.

Here is the code I am using:

        UploadConfiguration uploadConfiguration = UploadConfiguration.builder()
                        .allowMultipartUploads(true)
                        .allowParallelUploads(true)
                        .build();

        UploadManager uploadManager = new UploadManager(client, uploadConfiguration);

        PutObjectRequest request =
                PutObjectRequest.builder()
                        .namespaceName(namespaceName)
                        .bucketName(bucketName)
                        .objectName(objectName)
                        .contentType(null)
                        .contentLanguage(null)
                        .contentEncoding(null)
                        .opcMeta(null)
                        .build();

        UploadManager.UploadRequest uploadDetails =
                UploadManager.UploadRequest.builder(file).allowOverwrite(true).build(request);

        UploadManager.UploadResponse response = uploadManager.upload(uploadDetails);

**Comment by jodoglevy** [comment]
Thanks for reporting this issue @gyanshankar.

Does the same issue happen if you use the latest version of the SDK (1.5.0)?

If so, can you provide a request id that we can pass to the Object Storage team, so they can look into this issue more closely?

**Comment by gyanshankar** [comment]
I am unable to upgrade due to other dependency issues, switching to use swift api. Closing bug

**Comment by jodoglevy** [comment]
@gyanshankar  what dependency issues are you running into that prevent you from upgrading? Hoping we can help with that.

Even besides upgrading the SDK, if you can provide a request id that we can pass to the Object Storage team, from the SDK version you are on now, we can hopefully still resolve this.

**Comment by gyanshankar** [comment]
@jodoglevy I am trying again to use the sdk. Here is a request id

com.oracle.bmc.model.BmcException: (411, ContentLengthRequired, false) The Content-Length header is required (opc-request-id: f11e48d5-066a-6fbc-30f2-81a763d5f1a0)

**Comment by jodoglevy** [comment]
Thanks, I will engage the Object Storage team.

@gyanshankar what dependency issues are you running into that prevent you from upgrading?

**Comment by gyanshankar** [comment]
@jodoglevy Finally, I figured it out, I had to use Apache client configurator. Now it works fine.

**Comment by rsingareddy** [comment]
I have received error while storing object , while using oci-java-sdk-1.5.17 version
com.oracle.bmc.model.BmcException: (411, ContentLengthRequired, false) The Content-Length header is required (opc-request-id: 5914c75d-8bc8-0e77-0ef8-206eb3203a1c)
Here is the code

PutObjectRequest putObjectRequest = PutObjectRequest.builder().namespaceName(namespaceName).bucketName(bucket)
				.objectName(object).contentLength(contentLength).putObjectBody(stream)
				.build();

UploadConfiguration uploadConfiguration = UploadConfiguration.builder().minimumLengthForMultipartUpload(10)
				.lengthPerUploadPart(10).build();
		UploadManager uploadManager = new UploadManager(client, uploadConfiguration) {
			@Override
			protected MultipartObjectAssembler createAssembler(PutObjectRequest request, UploadRequest uploadRequest,
					ExecutorService executorService) {
				return assembler;
			}
		};

UploadRequest uploadRequest = UploadRequest.builder(stream, contentLength).progressReporter(null)
				.build(putObjectRequest);

UploadResponse uploadResponse = uploadManager.upload(uploadRequest);

Any idea @jodoglevy ?

**Comment by jodoglevy** [comment]
@rsingareddy this issue has been closed for 4 months. Can you please open a new GitHub issue for your issue?
