### ISSUE TITLE
HTTP header warnings with verison 1.5.2

### ISSUE THREAD

**Issue by aalmiray** [oracle/oci-java-sdk#121]
From time to time I get the following message on the console

    Attempt to send restricted header(s) while the [sun.net.http.allowRestrictedHeaders] system property not set. Header(s) will possibly be ignored.

I'm using version `1.5.2` with the http://github.com/aalmiray/oci-gradle-plugin/ plugin, which consumes all third party libraries as is https://github.com/aalmiray/oci-gradle-plugin/blob/master/plugins/oci-gradle-plugin/oci-gradle-plugin.gradle#L31-L78

Is there a way to remove this warning?

**Comment by sumitkdey** [comment]
The `DefaultConfigurator` sets this system property to true. See https://github.com/oracle/oci-java-sdk/blob/master/bmc-common/src/main/java/com/oracle/bmc/http/DefaultConfigurator.java#L45-L46. If you use the raw request signer, you would need to set this property yourself as demonstrated in https://github.com/oracle/oci-java-sdk/blob/master/bmc-examples/src/main/java/RawRestCallExample.java#L30-L32

**Comment by aalmiray** [comment]
Thanks!
