### ISSUE TITLE
Is the Java SDK Thread Safe?

### ISSUE THREAD

**Issue by TTJudy** [oracle/oci-java-sdk#122]
Would it be any issue if I write multi-threaded program to call the Java SDK? Is the Java SDK client thread safe?

**Comment by sumitkdey** [comment]
As documented in https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/javasdkconcepts.htm#ThreadingModel, the SDK clients are thread-safe after they are initialized. Once you have called `setEndpoint` or `setRegion` on the client, different threads can call apis on it in parallel.
