### ISSUE TITLE
Couldn't find a documentation

### ISSUE THREAD

**Issue by MichiFrech** [oracle/oci-java-sdk#136]
I am searching for a documentation for this java-sdk, but I couldn't find one. For Ruby, Python and Go, there is a good documentation but I only found the API Reference for Java.

**Comment by arthall** [comment]
Here is the documentation for the Java SDK.  https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/javasdk.htm

**Comment by arthall** [comment]
@MichiFrech Did the link provide the documentation you wanted?  I'm going to close this issue, but please reopen it if that is not the documentation for which you were looking.
