### ISSUE TITLE
OCI-java-sdk shaded version for JDK 11

### ISSUE THREAD

**Issue by ekumen** [oracle/oci-java-sdk#138]
I see below errors when I use JDK 11 to run shaded OCI-java-sdk library. I understand it is because javax.activation, jaxb/(api,impl,core) is removed from JDK11. Do we have a plan to add these libraries to be shaded? Thanks!

> Jul 03, 2019 6:34:17 PM shaded.com.oracle.oci.javasdk.org.glassfish.jersey.internal.Errors logErrors
> WARNING: The following warnings have been detected: WARNING: HK2 failure has been detected in a code that does not run in an active Jersey Error scope.
> WARNING: HK2 service reification failed for [shaded.com.oracle.oci.javasdk.org.glassfish.jersey.message.internal.DataSourceProvider] with an exception:
> MultiException stack 1 of 2
> java.lang.NoClassDefFoundError: javax/activation/DataSource
>         at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
>         at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3138)
>         at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2358)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1378)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1374)
>         at java.base/java.security.AccessController.doPrivileged(Native Method)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.Utilities.getAllConstructors(Utilities.java:1374)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.Utilities.findProducerConstructor(Utilities.java:1317)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.DefaultClassAnalyzer.getConstructor(DefaultClassAnalyzer.java:83)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.inject.hk2.JerseyClassAnalyzer.getConstructor(JerseyClassAnalyzer.java:148)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.Utilities.getConstructor(Utilities.java:180)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:129)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:180)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.SystemDescriptor.internalReify(SystemDescriptor.java:740)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:694)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:464)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2310)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ServiceLocatorImpl.access$1200(ServiceLocatorImpl.java:128)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1395)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1390)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.hk2.utilities.cache.internal.WeakCARCacheImpl.compute(WeakCARCacheImpl.java:128)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1452)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1377)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1366)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:158)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:54)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:329)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.internal.inject.Providers.getProviders(Providers.java:157)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.message.internal.MessageBodyFactory.initialize(MessageBodyFactory.java:265)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.message.internal.MessageBodyFactory$MessageBodyWorkersConfigurator.postInit(MessageBodyFactory.java:136)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.ClientConfig$State.lambda$initRuntime$2(ClientConfig.java:470)
>         at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:470)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:419)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:319)
>         at com.oracle.bmc.http.internal.ForwardingInvocationBuilder.get(ForwardingInvocationBuilder.java:126)
>         at com.oracle.bmc.http.internal.RestClient.get(RestClient.java:102)
>         at com.oracle.bmc.objectstorage.ObjectStorageClient.getNamespace(ObjectStorageClient.java:696)
>         ... 58 more
> MultiException stack 2 of 2
> java.lang.IllegalArgumentException: Errors were discovered while reifying SystemDescriptor(
>         implementation=shaded.com.oracle.oci.javasdk.org.glassfish.jersey.message.internal.DataSourceProvider
>         contracts={shaded.com.oracle.oci.javasdk.javax.ws.rs.ext.MessageBodyWriter,shaded.com.oracle.oci.javasdk.javax.ws.rs.ext.MessageBodyReader}
>         scope=shaded.com.oracle.oci.javasdk.javax.inject.Singleton
>         qualifiers={}
>         descriptorType=CLASS
>         descriptorVisibility=NORMAL
>         metadata=
>         rank=0
>         loader=null
>         proxiable=null
>         proxyForSameScope=null
>         analysisName=null
>         id=14
>         locatorId=0
>         identityHashCode=1046336244
>         reified=false)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:705)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:464)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2310)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ServiceLocatorImpl.access$1200(ServiceLocatorImpl.java:128)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1395)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1390)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.hk2.utilities.cache.internal.WeakCARCacheImpl.compute(WeakCARCacheImpl.java:128)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1452)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1377)
>         at shaded.com.oracle.oci.javasdk.org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1366)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:158)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:54)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:329)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.internal.inject.Providers.getProviders(Providers.java:157)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.message.internal.MessageBodyFactory.initialize(MessageBodyFactory.java:265)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.message.internal.MessageBodyFactory$MessageBodyWorkersConfigurator.postInit(MessageBodyFactory.java:136)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.ClientConfig$State.lambda$initRuntime$2(ClientConfig.java:470)
>         at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:470)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:419)
>         at shaded.com.oracle.oci.javasdk.org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:319)
>         at com.oracle.bmc.http.internal.ForwardingInvocationBuilder.get(ForwardingInvocationBuilder.java:126)
>         at com.oracle.bmc.http.internal.RestClient.get(RestClient.java:102)
>         at com.oracle.bmc.objectstorage.ObjectStorageClient.getNamespace(ObjectStorageClient.java:696)
>        ....

**Comment by andy-miles** [comment]
This scenario is no different from any other java library that depends on the javax libraries when using Java 9+.  You should be able to add the required javax.* jars into your application's classpath to get it working.

The following dependencies should also pull in the transitive dependencies for it work:
```
<dependency>
    <groupId>javax.ws.rs</groupId>
    <artifactId>javax.ws.rs-api</artifactId>
    <version>2.1</version>
</dependency>
<dependency>
    <groupId>javax.validation</groupId>
    <artifactId>validation-api</artifactId>
    <version>1.1.0.Final</version>
</dependency>
<dependency>
    <groupId>javax.activation</groupId>
    <artifactId>activation</artifactId>
    <version>1.1.1</version>
</dependency>
```

Otherwise, I don't see a compelling use-case that would necessitate the inclusion of those libraries within the shaded SDK jar that we vend unless there is a compatibility issue with the newer versions. Is your application not working with the our SDK when you include the required JARs?

**Comment by ekumen** [comment]
Yes, it works. I asked just to make sure these jars not included is on purpose, not missed. Thanks!

**Comment by andy-miles** [comment]
Glad to hear that it works.  Please let us know if you run into issues with those jars in the future in case we need to reconsider its inclusion in the shaded jar.
