### ISSUE TITLE
UploadObject not working on Wildfly server

### ISSUE THREAD

**Issue by srinuydlp** [oracle/oci-java-sdk#143]
Hi
I am getting exception while creating client on UploadObject class which I am running as part of server i.e Wildfly 9
When I run it as standalone program it was working fine 
I am getting nosuchalgoritham exception
Thanks

**Comment by andy-miles** [comment]
Could you please provide more information including:
1. OCI Java SDK version
2. JAVA runtime version
3. Full stack trace of the exception with any sensitive information omitted.

**Comment by andy-miles** [comment]
I'll leave this issue open for another week.  If I don't see a reply by then, I'll close out this issue.

**Comment by andy-miles** [comment]
I'm closing this issue.  Please reopen if you are still having issues.
