### ISSUE TITLE
Exception in thread "main" java.lang.SecurityException: class "com.oracle.bmc.http.ResteasyClientConfigurator"'s signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by srinuydlp** [oracle/oci-java-sdk#144]
Exception in thread "main" java.lang.SecurityException: class "com.oracle.bmc.http.ResteasyClientConfigurator"'s signer information does not match signer information of other classes in the same package

I am getting this exception while running ResteasyClientWithObjectStorageExample java class

**Comment by Jay-ArBrouillard** [comment]
What was the resolution here? I get the same error using oci-java-sdk-shaded-full-3.6.0.jar.

Exception in thread "main" java.lang.SecurityException: class "org.bouncycastle.openssl.PEMParser"'s signer information does not match signer information of other classes in the same package. 

The following third-party jars are also added as dependency:
bcpkix-jdk15on-1.70.jar
bcprov-jdk15on-1.70.jar
bcutil-jdk15on-1.70.jar
slf4j-api-1.7.33.jar

This is the code:
`    final AuthenticationDetailsProvider authenticationDetailsProvider;

    // Read private key file
    Supplier<InputStream> privateKeySupplier = new SimplePrivateKeySupplier(pContext.getPrivateKeyPath());


    if (FlexCommonUtils.isNotEmpty(pContext.getKeyPassphrase()))
    {
      authenticationDetailsProvider =
        SimpleAuthenticationDetailsProvider.builder().tenantId(pContext.getTenancyId()).userId(pContext.getUserId()).fingerprint(pContext.getKeyFingerprint()).privateKeySupplier(privateKeySupplier).passPhrase(pContext.getKeyPassphrase()).build();
    }
    else
    {
      authenticationDetailsProvider =
        SimpleAuthenticationDetailsProvider.builder().tenantId(pContext.getTenancyId()).userId(pContext.getUserId()).fingerprint(pContext.getKeyFingerprint()).privateKeySupplier(privateKeySupplier).build();
    }

    mDeploymentClient = DeploymentClient.builder().region(Region.valueOf(pContext.getRegion())).build(authenticationDetailsProvider);`

**Comment by Jay-ArBrouillard** [comment]
> What was the resolution here? I get the same error using oci-java-sdk-shaded-full-3.6.0.jar.
> 
> Exception in thread "main" java.lang.SecurityException: class "org.bouncycastle.openssl.PEMParser"'s signer information does not match signer information of other classes in the same package.
> 
> The following third-party jars are also added as dependency: bcpkix-jdk15on-1.70.jar bcprov-jdk15on-1.70.jar bcutil-jdk15on-1.70.jar slf4j-api-1.7.33.jar
> 
> This is the code: ` final AuthenticationDetailsProvider authenticationDetailsProvider;
> 
> ```
> // Read private key file
> Supplier<InputStream> privateKeySupplier = new SimplePrivateKeySupplier(pContext.getPrivateKeyPath());
> 
> 
> if (FlexCommonUtils.isNotEmpty(pContext.getKeyPassphrase()))
> {
>   authenticationDetailsProvider =
>     SimpleAuthenticationDetailsProvider.builder().tenantId(pContext.getTenancyId()).userId(pContext.getUserId()).fingerprint(pContext.getKeyFingerprint()).privateKeySupplier(privateKeySupplier).passPhrase(pContext.getKeyPassphrase()).build();
> }
> else
> {
>   authenticationDetailsProvider =
>     SimpleAuthenticationDetailsProvider.builder().tenantId(pContext.getTenancyId()).userId(pContext.getUserId()).fingerprint(pContext.getKeyFingerprint()).privateKeySupplier(privateKeySupplier).build();
> }
> 
> mDeploymentClient = DeploymentClient.builder().region(Region.valueOf(pContext.getRegion())).build(authenticationDetailsProvider);`
> ```

Nevermind, there was duplicate dependency I found now. Thanks.
