### ISSUE TITLE
How to play video file from private bucket object store through oci-java-sdk

### ISSUE THREAD

**Issue by rsingareddy** [oracle/oci-java-sdk#148]
It is straight forward to play video from public object storage bucket using video player. Looking for example to play video from private object storage bucket using OCI-Java-SDK.

**Comment by rsingareddy** [comment]
Reopening the issue. Here is the video player with the Oracle Object Store URL.

<video playsinline="true" controls="true" 
class="data-dashjs-player" id="myvideo" width="600" height="400" 
oncontextmenu="javascript:return false;"> 
<source type="video/mp4" 
src="https://objectstorage.us-ashburn-1.oraclecloud.com/n/<namespace>/b/<bucket>/o/myvideo.mp4 " /> 
</video> 

When we sign URL, Do we need send Signature and keyId parameters along with URL for access?

https://objectstorage.us-ashburn-1.oraclecloud.com/n/<namespace>/b/<bucket>/o/myvideo.mp4?keyId="...."&Signature=".."?

**Comment by jodoglevy** [comment]
You can't have the browser send or construct the authorization header needed to access private objects using the <source> element pointing directly to the Object Storage url.

Your options are:
- Make the object publicly accessible
- Create a [pre-authenticated request](https://docs.cloud.oracle.com/iaas/Content/Object/Tasks/usingpreauthenticatedrequests.htm) pointing to the object, and reference that in the <source> element
- Have the <source> element reference a link to your own web service, which, when it receives a request, takes the info in the request and uses it to download in the web service (in an authenticated fashion) the object, and then responds to the request it received with that object's payload

**Comment by andy-miles** [comment]
Based on @jodoglevy's solutions cited above, I'm going to close this issue.  If you continue to have questions and/or concerns, please re-open this issue.
