### ISSUE TITLE
Weak Cryptographic Hash：SHA-1

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [oracle/oci-java-sdk#156]
https://github.com/oracle/oci-java-sdk/blob/de21beecbc7901928991c27e2f584c1cfe241896/bmc-common/src/main/java/com/oracle/bmc/auth/internal/AuthUtils.java#L58
Weak cryptographic hashes cannot guarantee data integrity and should not be used in security-critical contexts.

**Comment by andy-miles** [comment]
The cited use of SHA-1 is used for the fingerprint of a key.   It does not pose a security risk as it's not used as the primary means of authentication.
