### ISSUE TITLE
Java 11 with oci java sdk

### ISSUE THREAD

**Issue by jinzha** [oracle/oci-java-sdk#162]
Hi,

When I use Java 11 with oci-java-sdk, I got below warning. It looks like java 11 is not valid version for oci java sdk. Is there any special reason that java 11 is not valid version? If use 11, is there any risk? 

**WARNING: Using an unknown runtime, calls may not work**

**Comment by andy-miles** [comment]
We have an item on our backlog to evaluate and upgrade support for newer versions of Java.   As of today, it is tested and supported with JDK 8.  In the mean time, please feel free to test and let us know if you run into issues using Java 11 with the SDK.

**Comment by jaytaylor** [comment]
Other than needing to follow [these instructions](https://github.com/highsource/jsonix-schema-compiler/issues/81#issuecomment-450059488) to pull in the javax.*.bind and sun.*.bind dependencies, the OCI SDK is working on JDK11 without any issues for me.

Please consider prioritizing testing and validating the OCI SDK; JDK11 brings a ton of benefits over JDK8.

Thank you!

**Comment by jaytaylor** [comment]
Other than needing to follow [these instructions](https://github.com/highsource/jsonix-schema-compiler/issues/81#issuecomment-450059488) to pull in the `javax.*.bind` and `sun.*.bind` dependencies, the OCI SDK is working great for us on JDK11.

Please consider prioritizing testing and validating the OCI SDK on 11; JDK11 brings a ton of benefits over JDK8.

Thank you!

**Comment by omkar07** [comment]
Hi @jinzha and @jaytaylor , We have tested OCI JAVA SDK on JDK11 and have tests in place for the releases which we do weekly. Also, updated docs for JDK11 support can be found here: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/javasdk.htm . Closing this issue since the ask is complete.

Thank you!

**Comment by Madzi** [comment]
The same issue appears for application build with jlink. The application with JDK 17 works fine, but when I build application with jlink, application failed with this error.
