### ISSUE TITLE
is it possible to push messages from PL/SQL?

### ISSUE THREAD

**Issue by marionagy** [oracle/oci-java-sdk#166]
I was requested to adjust our PL/SQL program on GSI to use OCI streaming service.
This code push messages using a REST service.
Could somebody provide  an example for the message pushing from PL/SQL using Streaming service, please?

**Comment by jodoglevy** [comment]
Update: we have reached out to the Database service team on this

**Comment by marionagy** [comment]
Thanks. 
The cUrl [walkthrough](https://www.ateam-oracle.com/oracle-cloud-infrastructure-oci-rest-call-walkthrough-with-curl) helps a lot. REST api call is not hard to implement based on this.
But the authentication signature is tricky. Basic SHA256 is easy with dbms_crypto package, but I haven't found a way to sign with RSA key within PL/SQL.
My tests get "NotAuthenticated" response.
I'm experimenting with a java language source code currently found here:
https://www.quickprogrammingtips.com/java/how-to-create-sha256-rsa-signature-using-java.html

**Comment by jodoglevy** [comment]
The Database team is working on a simple wrapper procedure to do any OCI REST API call. Users will have to provide required headers and interpret responses. This will be documented for Autonomous Database customers in the next few weeks.

**Comment by mricken** [comment]
The Database team has implemented this and is currently writing the documentation. Early in January, we will be able to point you to the documentation.

**Comment by marionagy** [comment]
Great news, I'm looking forward to it.
I've managed to implement the signing procedure using a java language code. 
But I'll be happy to switch to the official version when it will be available.

**Comment by mricken** [comment]
Hi @marionagy,

Here is the documentation that I've been shown:

https://docs.oracle.com/en/cloud/paas/autonomous-data-warehouse-cloud/user/dbms-cloud-rest.html#GUID-19B1639E-68E2-45BB-802C-817ABD0DBE88

https://docs.oracle.com/en/cloud/paas/atp-cloud/atpug/dbms-cloud-rest.html#GUID-19B1639E-68E2-45BB-802C-817ABD0DBE88

Please let us know if this helps.

Thanks!

**Comment by mricken** [comment]
@marionagy , I'm closing this issue, since the DBaaS team has implemented the functionality and I have provided documentation. If you have further questions, please feel free to re-open this issue.
