### ISSUE TITLE
Exception when creating a bucket

### ISSUE THREAD

**Issue by aalmiray** [oracle/oci-java-sdk#178]
I'm having trouble with bucket operations, perhaps I misunderstood some of the operations. The following code first queries if a given bucket exists on a particular namespace/compartment and returns immediately if that's the case, else it attempts to create the bucket on said namespace/compartment

    private void ensureBucketExists() {
        // 1. Check if it exists
        try {
            List<BucketSummary> bucketSummaries = client.listBuckets(ListBucketsRequest.builder()
                .compartmentId(buildCache.compartmentId)
                .namespaceName(namespaceName)
                .build()).items
            BucketSummary bucketSummary = bucketSummaries.find { BucketSummary c -> c.name == buildCache.bucket }

            if (bucketSummary) {
                logger.info("Bucket '${buildCache.bucket}' was found.")
                ensureLifecyclePolicyExists()
                return
            }
        } catch (BmcException e) {
            throw new BuildCacheException("Error while resolving ${namespaceName}:$buildCache.bucket} bucket", e)
        }

        // 2. Create bucket
        logger.info('Provisioning Bucket. This may take a while.')
        try {
            client.createBucket(CreateBucketRequest.builder()
                .namespaceName(namespaceName)
                .createBucketDetails(CreateBucketDetails.builder()
                    .compartmentId(buildCache.compartmentId)
                    .name(buildCache.bucket)
                    .build())
                .build())
        } catch (BmcException e) {
            throw new BuildCacheException("Error while provisioning ${namespaceName}:$buildCache.bucket} bucket", e)
        }

        // 3. Create lifecycle policy
        createObjectLifecyclePolicy([createObjectLifecycleRule()])
    }

Now, I have the following compartment hierarchy

    . root
    |---- samples
    \---- build

As it turns out I had a bucket named `build-cache` associated with the `samples` compartment before I ran a test. Executing the aforementioned code results in an exception

    com.oracle.bmc.model.BmcException: (409, BucketAlreadyExists, false) Either the bucket 'build-cache' in namespace 'aalmiray' already exists or you are not authorized to create it (opc-request-id: fra-1:yQY6L-Ss-Ov64skbh12FT9yEqLoQtTx3ZI-VRwbL3RlIZuf-9qKlWitAffF19n7C)

It appears to me that bucket names must be unique within a namespace, is that correct? If so what would be the correct way to check that a bucket exists on a namespace regardless of its associated compartment?

**Comment by priteshkp** [comment]
Correct, a bucket is unique in the namespace, not in the compartment.

To check if a bucket exists, you can use the HeadBucket operation instead (specifying namespace and bucket name only).  It should throw an exception if it doesn't exist, or return some metadata if it does.

**Comment by aalmiray** [comment]
Thanks!
