### ISSUE TITLE
OCI Java SDK : Http Proxy not working

### ISSUE THREAD

**Issue by deepakac** [oracle/oci-java-sdk#187]
I tried using proxy as in sample - https://github.com/oracle/oci-java-sdk/blob/master/bmc-examples/src/main/java/HttpProxyExample.java. I am getting connect timeout exception to the objectstorage url

07:21:30.749 [main] INFO com.oracle.bmc.auth.URLBasedX509CertificateSupplier - suppressX509Workaround flag set to false
07:21:41.683 [main] DEBUG com.oracle.bmc.http.signing.internal.PEMFileRSAPrivateKeySupplier - Initializing private key
ocid1.tenancy.oc1..aaaaaaaa4yafecztqbebznfxpjzwm52wuaeornzgzqrujpbkmeez6zuigv7a
07:21:47.190 [main] INFO com.oracle.bmc.Services - Registering new service: Services.BasicService(serviceName=AUTH, serviceEndpointPrefix=auth, serviceEndpointTemplate=null)
07:21:49.179 [main] INFO com.oracle.bmc.util.JavaRuntimeUtils - Determined JRE version as Java_8
07:21:49.179 [main] INFO com.oracle.bmc.http.DefaultConfigurator - Setting connector provider to HttpUrlConnectorProvider
07:21:49.457 [main] INFO com.oracle.bmc.Services - Registering new service: Services.BasicService(serviceName=OBJECTSTORAGE, serviceEndpointPrefix=objectstorage, serviceEndpointTemplate=https://objectstorage.{region}.{secondLevelDomain})
07:21:49.462 [main] INFO com.oracle.bmc.Region - Loaded service 'OBJECTSTORAGE' endpoint mappings: {CA_TORONTO_1=https://objectstorage.ca-toronto-1.oraclecloud.com}
07:21:49.469 [main] INFO com.oracle.bmc.http.ApacheConfigurator - Setting connector provider to ApacheConnectorProviders
07:21:49.470 [main] DEBUG com.oracle.bmc.http.ApacheProxyConfigDecorator - ApacheProxyConfig: [uri: http://ch3-opc-proxy.usdc2.oraclecloud.com:80, username: null, password: null]
07:21:49.470 [main] INFO com.oracle.bmc.http.ApacheProxyConfigDecorator - Configuring proxy for ApacheConnectorProvider to connect to http://ch3-opc-proxy.usdc2.oraclecloud.com:80
07:21:49.470 [main] INFO com.oracle.bmc.http.ApacheProxyConfigDecorator - Either username or password is null. Not configuring auth credentials for the proxy
07:21:49.476 [main] INFO com.oracle.bmc.objectstorage.ObjectStorageClient - Setting endpoint to https://objectstorage.ca-toronto-1.oraclecloud.com
Fetching bucket details
07:21:49.504 [main] DEBUG com.oracle.bmc.http.internal.RestClient - Generated request ID: 630B1F98BF2243BAB1217B9E0181974F
07:21:49.887 [main] DEBUG com.oracle.bmc.auth.internal.SecurityTokenAdapter - Security token is not valid.
07:21:49.887 [main] DEBUG com.oracle.bmc.auth.internal.SecurityTokenAdapter - Security token is not valid.
07:21:49.887 [main] INFO com.oracle.bmc.auth.internal.X509FederationClient - Refreshing session keys.
07:22:00.744 [main] DEBUG com.oracle.bmc.http.signing.internal.PEMFileRSAPrivateKeySupplier - Initializing private key
07:22:05.926 [main] INFO com.oracle.bmc.auth.internal.X509FederationClient - Getting security token from the auth server
07:22:05.926 [main] DEBUG com.oracle.bmc.auth.internal.X509FederationClient - Intermediate certificate(s) were supplied
07:22:05.940 [main] DEBUG com.oracle.bmc.http.internal.RestClient - Generated request ID: 03CA60C468CB4420A20BD6E3E1468306
07:22:06.210 [main] INFO com.oracle.bmc.ClientRuntime - Using SDK: Oracle-JavaSDK/1.12.2
07:22:06.210 [main] INFO com.oracle.bmc.ClientRuntime - User agent set to: Oracle-JavaSDK/1.12.2 (Linux/2.6.39-400.109.6.el6uek.x86_64; Java/1.8.0_60; Java HotSpot(TM) 64-Bit Server VM/25.60-b23)
07:22:06.210 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending 'POST' request to 'https://auth.ca-toronto-1.oraclecloud.com/v1/x509'
07:22:06.210 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'opc-request-id' with value '[03CA60C468CB4420A20BD6E3E1468306]'
07:22:06.211 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'Content-Type' with value '[application/json]'
07:22:06.211 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'date' with value '[Thu, 16 Jan 2020 07:22:06 GMT]'
07:22:06.211 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'authorization' with value '[Signature headers="date (request-target) content-length content-type x-content-sha256",keyId="ocid1.tenancy.oc1..aaaaaaaa4yafecztqbebznfxpjzwm52wuaeornzgzqrujpbkmeez6zuigv7a/fed-x509/3F:C6:C5:3C:63:AC:70:D3:B6:D4:DB:9E:8E:98:F6:7B:59:C1:98:DA",algorithm="rsa-sha256",signature="sKp7oLoh/+vrw/rBdXDgmtDoYReh9ltDIeHfgxeKg2nnJ1piT463jRLtsIdEvy+f8mcaR5o7OYwAOWpdolxggncg8UAnrhtkQmD443uMXKaOGl/vtFZnl/oBPXyMMx4zIwTD8hJXcBjm6UzT5zC2q/4bsli6DOnhfgsUuyUFDl40bZpL/u6A7tzSiTSB4po4dms1bdWaG//YQqponAK3aKSIQKLOnAWOypJDKhOzCAAbfIZ1izuKPyqPdJS8efEXxuafB8ljhNRTjQ4RC/YtKNVTPhPSAN11c662VVr1RTRSpOZfcVowfnPQ4pgQ2bISzRCii/sU1QlzJoT3KQTlwg==",version="1"]'
07:22:06.211 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'content-length' with value '[5267]'
07:22:06.211 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'x-content-sha256' with value '[E4MsWOB3YDwnXqDntoYu6vwLEWeZPJhx3lT5KHOKbsg=]'
07:22:06.212 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'opc-retry-token' with value '[49f24e53-8f7c-43e1-bb20-1ebf06f2b97d]'
07:22:06.212 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'User-Agent' with value '[Oracle-JavaSDK/1.12.2 (Linux/2.6.39-400.109.6.el6uek.x86_64; Java/1.8.0_60; Java HotSpot(TM) 64-Bit Server VM/25.60-b23)]'
07:22:06.212 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'opc-client-info' with value '[Oracle-JavaSDK/1.12.2]'
07:22:16.604 [main] DEBUG com.oracle.bmc.http.internal.RestClient - User-set request ID: 03CA60C468CB4420A20BD6E3E1468306
07:22:16.628 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending 'POST' request to 'https://auth.ca-toronto-1.oraclecloud.com/v1/x509'
07:22:16.628 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'opc-request-id' with value '[03CA60C468CB4420A20BD6E3E1468306]'
07:22:16.628 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'Content-Type' with value '[application/json]'
07:22:16.629 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'date' with value '[Thu, 16 Jan 2020 07:22:16 GMT]'
07:22:16.629 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'authorization' with value '[Signature headers="date (request-target) content-length content-type x-content-sha256",keyId="ocid1.tenancy.oc1..aaaaaaaa4yafecztqbebznfxpjzwm52wuaeornzgzqrujpbkmeez6zuigv7a/fed-x509/3F:C6:C5:3C:63:AC:70:D3:B6:D4:DB:9E:8E:98:F6:7B:59:C1:98:DA",algorithm="rsa-sha256",signature="qMBzMDV6703iPUDVGtEXd6i6ySCbJP6dG5+qPh8CxwmxsYSjeV/dC8yAHVF1JCdGuA1F+V+h5Wc5BwBgNslE6x3kR6soDtC1pqp3CztKbXEfCsgWZZKyr1d2Si28y4vihqy0FvlMOo89Xy6zUiWiDIf4a+XmRu7WQBXddd1iMdl5uUWmqE4Oknpfkm51din7T48gfAQUdOGRdlqpbT3yONC2QokuYLAqPmvMqjkeVfWSj0tD1EyO0VmsyeuwF5p3gwuOw0TcaPhmCUnboRSQB/hEEwB4Fbs5wN+6F9w34z3NyFl7jsJ0BUHDwef0LIZ42Ixqzzun65urLM14vTpHqA==",version="1"]'
07:22:16.629 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'content-length' with value '[5267]'
07:22:16.629 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'x-content-sha256' with value '[E4MsWOB3YDwnXqDntoYu6vwLEWeZPJhx3lT5KHOKbsg=]'
07:22:16.629 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'opc-retry-token' with value '[45262eb9-e94c-426a-9648-5490a5cd719f]'
07:22:16.629 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'User-Agent' with value '[Oracle-JavaSDK/1.12.2 (Linux/2.6.39-400.109.6.el6uek.x86_64; Java/1.8.0_60; Java HotSpot(TM) 64-Bit Server VM/25.60-b23)]'
07:22:16.629 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'opc-client-info' with value '[Oracle-JavaSDK/1.12.2]'
07:22:26.895 [main] DEBUG com.oracle.bmc.http.internal.RestClient - User-set request ID: 03CA60C468CB4420A20BD6E3E1468306
07:22:26.913 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending 'POST' request to 'https://auth.ca-toronto-1.oraclecloud.com/v1/x509'
07:22:26.913 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'opc-request-id' with value '[03CA60C468CB4420A20BD6E3E1468306]'
07:22:26.913 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'Content-Type' with value '[application/json]'
07:22:26.913 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'date' with value '[Thu, 16 Jan 2020 07:22:26 GMT]'
07:22:26.914 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'authorization' with value '[Signature headers="date (request-target) content-length content-type x-content-sha256",keyId="ocid1.tenancy.oc1..aaaaaaaa4yafecztqbebznfxpjzwm52wuaeornzgzqrujpbkmeez6zuigv7a/fed-x509/3F:C6:C5:3C:63:AC:70:D3:B6:D4:DB:9E:8E:98:F6:7B:59:C1:98:DA",algorithm="rsa-sha256",signature="wYuT/9AGcgt1BzhhmBBtkyP1SuVx8OIU6vDbAv348bG41YS39qYutecSaz4qxFTUt/7IpFUcl0oFekBg4HgXLwHdpfwFRE+oMegoo1IVUtY+k/hgne20z8rBqsw35+o9pbS5dspBoI3Rkg4jNiBwN69YR6k49NFGLNJwFA1uaX6sN/VUqiQtOu3NSAU2cK68NKVnb+B1PnGmJRK7MgMpzv2OWWWRyyoX7oT9rhhuyr2/EC+Gywx76E4brHWNZpxwiebecYFM51sCUqQuVI/EwrMOZFoWz+EcElEwOXwt8NIm1ixzF+NyrgGvUGXXM4Brb2XNLvxKJuq+H6KHkWfvNg==",version="1"]'
07:22:26.914 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'content-length' with value '[5267]'
07:22:26.914 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'x-content-sha256' with value '[E4MsWOB3YDwnXqDntoYu6vwLEWeZPJhx3lT5KHOKbsg=]'
07:22:26.914 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'opc-retry-token' with value '[c54fcf88-ddd7-44ee-b32e-5121c5793085]'
07:22:26.914 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'User-Agent' with value '[Oracle-JavaSDK/1.12.2 (Linux/2.6.39-400.109.6.el6uek.x86_64; Java/1.8.0_60; Java HotSpot(TM) 64-Bit Server VM/25.60-b23)]'
07:22:26.914 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'opc-client-info' with value '[Oracle-JavaSDK/1.12.2]'
07:22:37.170 [main] DEBUG com.oracle.bmc.http.internal.RestClient - User-set request ID: 03CA60C468CB4420A20BD6E3E1468306
07:22:37.192 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending 'POST' request to 'https://auth.ca-toronto-1.oraclecloud.com/v1/x509'
07:22:37.192 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'opc-request-id' with value '[03CA60C468CB4420A20BD6E3E1468306]'
07:22:37.192 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'Content-Type' with value '[application/json]'
07:22:37.192 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'date' with value '[Thu, 16 Jan 2020 07:22:37 GMT]'
07:22:37.192 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'authorization' with value '[Signature headers="date (request-target) content-length content-type x-content-sha256",keyId="ocid1.tenancy.oc1..aaaaaaaa4yafecztqbebznfxpjzwm52wuaeornzgzqrujpbkmeez6zuigv7a/fed-x509/3F:C6:C5:3C:63:AC:70:D3:B6:D4:DB:9E:8E:98:F6:7B:59:C1:98:DA",algorithm="rsa-sha256",signature="R3VtihH4JxNj63u9d5lSaDgTYsVsGbUQ6fEfqgjYehUJv2m0Hi4jVU2MZqBj8zC19WbB2QxQaBjRnRiuPlZx96FVnPdKIlsehH/3Z4jnhLbutOMDzlqzSQ5kdPCZZj3lo+ERdQJDBVWt21T3Ub1K0iGg+yCpJ7l0ch75mxhNMCcgp31efymeA8lL+aLrn96g0+PvmYo/F1ux0leDcVvyn/1YefJdT9LXIVcrbDMAizQycy5tTKJb/A1C3+ClLaq++Kd3N6nX6l7Rsn6rfp4dnbYivvfpY9fO8YMR0hMM6PmAd1fUB7ENc3OowgYf3D0eHq6vvwnIUJN6gzraLUY86w==",version="1"]'
07:22:37.192 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'content-length' with value '[5267]'
07:22:37.193 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'x-content-sha256' with value '[E4MsWOB3YDwnXqDntoYu6vwLEWeZPJhx3lT5KHOKbsg=]'
07:22:37.193 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'opc-retry-token' with value '[3b43398b-1fc7-41fc-898a-e96253080eab]'
07:22:37.193 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'User-Agent' with value '[Oracle-JavaSDK/1.12.2 (Linux/2.6.39-400.109.6.el6uek.x86_64; Java/1.8.0_60; Java HotSpot(TM) 64-Bit Server VM/25.60-b23)]'
07:22:37.193 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'opc-client-info' with value '[Oracle-JavaSDK/1.12.2]'
07:22:47.530 [main] DEBUG com.oracle.bmc.http.internal.RestClient - User-set request ID: 03CA60C468CB4420A20BD6E3E1468306
07:22:47.546 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending 'POST' request to 'https://auth.ca-toronto-1.oraclecloud.com/v1/x509'
07:22:47.546 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'opc-request-id' with value '[03CA60C468CB4420A20BD6E3E1468306]'
07:22:47.546 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'Content-Type' with value '[application/json]'
07:22:47.546 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'date' with value '[Thu, 16 Jan 2020 07:22:47 GMT]'
07:22:47.547 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'authorization' with value '[Signature headers="date (request-target) content-length content-type x-content-sha256",keyId="ocid1.tenancy.oc1..aaaaaaaa4yafecztqbebznfxpjzwm52wuaeornzgzqrujpbkmeez6zuigv7a/fed-x509/3F:C6:C5:3C:63:AC:70:D3:B6:D4:DB:9E:8E:98:F6:7B:59:C1:98:DA",algorithm="rsa-sha256",signature="SzcXPuU4Mrt2st2biR1UgX0FsTb2gwnQa77fsL2t7QDV4GumDes1E40t/zrhacA9LwZHVzLZnF3ZJ5j/miVCt6Y8HilraccsdlnLXOj9w/Jmjhv5yKSfCbOfgrDOfJWAHhXHXW3nB53MfgiwGufsex9uubrnY7Rw54/zwUkSZT9pHPojlMH2fAYH6VrnnHDiPp/wInjBUOlndLfwWpVZc1//FtZvd8U7XH/mKSHcC1S9N8xw0oOeTVgdx5B81CSEepU7QiMdTV2Dg6uf45ugIWBA/IZ5uTfLND6SR9hikv3SZFZTa5UrfdEGivtVyiiLNxtkoWb16W63wWoPkT8rSA==",version="1"]'
07:22:47.547 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'content-length' with value '[5267]'
07:22:47.547 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'x-content-sha256' with value '[E4MsWOB3YDwnXqDntoYu6vwLEWeZPJhx3lT5KHOKbsg=]'
07:22:47.547 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'opc-retry-token' with value '[7700da35-f780-4f17-9316-35d282687d1d]'
07:22:47.547 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'User-Agent' with value '[Oracle-JavaSDK/1.12.2 (Linux/2.6.39-400.109.6.el6uek.x86_64; Java/1.8.0_60; Java HotSpot(TM) 64-Bit Server VM/25.60-b23)]'
07:22:47.547 [main] DEBUG com.oracle.bmc.http.internal.LogHeadersFilter - Sending header 'opc-client-info' with value '[Oracle-JavaSDK/1.12.2]'
Exception in thread "main" com.oracle.bmc.model.BmcException: (-1, null, true) Timed out while communicating to: https://objectstorage.ca-toronto-1.oraclecloud.com (outbound opc-request-id: 630B1F98BF2243BAB1217B9E0181974F)
        at com.oracle.bmc.http.internal.RestClient.convertToBmcException(RestClient.java:572)
        at com.oracle.bmc.http.internal.RestClient.get(RestClient.java:105)
        at com.oracle.bmc.objectstorage.ObjectStorageClient.listBuckets(ObjectStorageClient.java:899)
        at com.cec.s2s.S2SUsingInstancePrincipal.main(S2SUsingInstancePrincipal.java:113)
Caused by: javax.ws.rs.ProcessingException: (-1, null, true) Timed out while communicating to: https://auth.ca-toronto-1.oraclecloud.com (outbound opc-request-id: 03CA60C468CB4420A20BD6E3E1468306)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:261)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
        at com.oracle.bmc.http.internal.ForwardingInvocationBuilder.get(ForwardingInvocationBuilder.java:126)
        at com.oracle.bmc.http.internal.RestClient.get(RestClient.java:102)
        ... 2 more
Caused by: com.oracle.bmc.model.BmcException: (-1, null, true) Timed out while communicating to: https://auth.ca-toronto-1.oraclecloud.com (outbound opc-request-id: 03CA60C468CB4420A20BD6E3E1468306)
        at com.oracle.bmc.http.internal.RestClient.convertToBmcException(RestClient.java:572)
        at com.oracle.bmc.http.internal.RestClient.post(RestClient.java:156)
        at com.oracle.bmc.auth.internal.X509FederationClient.makeCall(X509FederationClient.java:287)
        at com.oracle.bmc.auth.internal.X509FederationClient.getSecurityTokenFromServer(X509FederationClient.java:268)
        at com.oracle.bmc.auth.internal.X509FederationClient.refreshAndGetSecurityTokenInner(X509FederationClient.java:196)
        at com.oracle.bmc.auth.internal.X509FederationClient.getSecurityToken(X509FederationClient.java:133)
        at com.oracle.bmc.auth.AbstractRequestingAuthenticationDetailsProvider.getKeyId(AbstractRequestingAuthenticationDetailsProvider.java:87)
        at com.oracle.bmc.http.signing.internal.DefaultRequestSignerFactory$1.get(DefaultRequestSignerFactory.java:71)
        at com.oracle.bmc.http.signing.internal.DefaultRequestSignerFactory$1.get(DefaultRequestSignerFactory.java:68)
        at com.oracle.bmc.http.signing.internal.RequestSignerImpl.signRequest(RequestSignerImpl.java:131)
        at com.oracle.bmc.http.signing.internal.RequestSignerImpl.signRequest(RequestSignerImpl.java:108)
        at com.oracle.bmc.http.internal.AuthnClientFilter.filter(AuthnClientFilter.java:49)
        at org.glassfish.jersey.client.ClientFilteringStages$RequestFilteringStage.apply(ClientFilteringStages.java:115)
        at org.glassfish.jersey.client.ClientFilteringStages$RequestFilteringStage.apply(ClientFilteringStages.java:103)
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
        ... 13 more
Caused by: javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: connect timed out
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:343)
        at com.oracle.bmc.http.internal.ForwardingInvocationBuilder.post(ForwardingInvocationBuilder.java:156)
        at com.oracle.bmc.http.internal.ForwardingInvocationBuilder.post(ForwardingInvocationBuilder.java:156)
        at com.oracle.bmc.http.internal.RestClient.post(RestClient.java:153)
        ... 27 more
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)

**Comment by mricken** [comment]
Thank you for reporting, we'll try to reproduce this.

**Comment by omkar07** [comment]
Hi Deepak, we have checked HttpProxyExample with the opc-proxy server you are using and it works as expected without any timeout exception. Please try again and confirm. Also, share your email id so that we can schedule a zoom call if you are still facing this issue.

**Comment by jodoglevy** [comment]
@deepakac are you still experiencing this issue?

**Comment by jodoglevy** [comment]
Hi @deepakac - since we haven't heard back from you, I'll be resolving this issue. But feel free to reopen this if you are still experiencing problems.
