### ISSUE TITLE
MD5 hash broken

### ISSUE THREAD

**Issue by Madzi** [oracle/oci-java-sdk#190]
For ListObjectRequest I received ObjectSummary(s) with information about object which contains also MD5 hash (base64 encoded).
For many objects the hash successfully was encoded but for some objects hash contains "-1" at the end of hash: "c62XUOjV/PeTZDNiC0uqIQ==-1"

**Comment by mricken** [comment]
Can you give us more information, please?

- What version of the OCI Java SDK are you using?
- If you look at the web console for those objects, what do you see as MD5 hash there?

When I'm looking at my own objects in Object Storage, I am seeing similar markers, both in the web console and the CLI. So this seems to be consistent across SDKs.

I'm therefore sending this to the Object Storage team for further explanation.

I assume it has something to do with this, though:

> opc-multipart-md5
> Only applicable to objects uploaded using multipart upload. Base-64 representation of the multipart object hash. The multipart object hash is calculated by taking the MD5 hashes of the parts, concatenating the binary representation of those hashes in order of their part numbers, and then calculating the MD5 hash of the concatenated values.

from https://docs.cloud.oracle.com/iaas/api/#/en/objectstorage/20160918/Object/GetObject

**Comment by Madzi** [comment]
Thank you for response.
I use version `1.12.2` (`1.12.3` now).
This behavior I see not for all objects. Tring to find any correlation.
Currently I'm cut received string to 24 chars and successfully decode it.

**Comment by Madzi** [comment]
My point is: hash received but with additional trash `-1` at the end. Looks like something happened during `json` conversion.

**Comment by mricken** [comment]
@Madzi , it should be for objects that were uploaded using the multi-part API (as opposed to PutObject).

**Comment by jodoglevy** [comment]
@mricken  is correct -- the trailing `-<n>` is only present for multipart-uploaded objects, and <n> is the number of parts.

I'm going to close this based on the response above. If you still have questions, please feel free to reopen this
