### ISSUE TITLE
Instance.getDisplayName() is null

### ISSUE THREAD

**Issue by sachin-pikle** [oracle/oci-java-sdk#195]
Hi, why is Instance.getDisplayName() is set to null? Also, I don't see any other field that has the name of a compute instance.

**Comment by jodoglevy** [comment]
Hi - we'll route this to the Compute team to provide an answer here

**Comment by sachin-pikle** [comment]
Hi @jodoglevy can we an update on this issue?

**Comment by jodoglevy** [comment]
@sachin-pikle  let me ping the Compute team again

**Comment by sachin-pikle** [comment]
Closing this issue. I can no longer reproduce it.
