### ISSUE TITLE
ConfigFileAuthenticationDetailsProvider doesn't have a method for the PEM file path

### ISSUE THREAD

**Issue by cartershanklin** [oracle/oci-java-sdk#207]
Per
https://docs.cloud.oracle.com/en-us/iaas/tools/java/1.12.0/com/oracle/bmc/auth/ConfigFileAuthenticationDetailsProvider.html

There's a method to get the private key bytes but not the path.

Meanwhile the HDFS connector for object store needs (it is mandatory) the PEM file path
https://docs.cloud.oracle.com/en-us/iaas/Content/API/SDKDocs/hdfsconnector.htm#Properties

I don't see any other obvious way to get the path in a robust way.

**Comment by priteshkp** [comment]
Note that the config file provider just using the following:
https://docs.cloud.oracle.com/en-us/iaas/tools/java/1.12.0/com/oracle/bmc/ConfigFileReader.html

That gives you a ConfigFile.  You can then ask the ConfigFile for any property, the provider just asks it for the path, reads it and turns it into bytes:
https://github.com/oracle/oci-java-sdk/blob/master/bmc-common/src/main/java/com/oracle/bmc/auth/ConfigFileAuthenticationDetailsProvider.java#L72

You could do the same thing if you need the path that was ultimately used.

**Comment by y-chandra** [comment]
`getPemFilePath()` method has been added to ConfigFileAuthenticationDetailsProvider.java:
https://github.com/oracle/oci-java-sdk/blob/f7199b91207c3e2b95b1ab7bfa9d1232b20e08bc/bmc-common/src/main/java/com/oracle/bmc/auth/ConfigFileAuthenticationDetailsProvider.java#L161
