### ISSUE TITLE
Start/Stop/create ADW

### ISSUE THREAD

**Issue by orcl1521** [oracle/oci-java-sdk#214]
Hi, 
I'm using the AutonomousDatawarehouseExample java example. 
I have a problem when starting / stopping and creating a new instant ADW.
I  created this sample code:

	public class AutonomousADW {

	    public static void main(String[] args) throws Exception {
	        String configurationFilePath = "/product/eclipse_workspace/OCI_CLOUD/config/config";
	        String profile = "DEFAULT";

	        if (args.length != 2) {
	            throw new IllegalArgumentException(
	                    String.format(
	                            "Unexpected number of arguments.  Expected 2, got %s", args.length));
	        }
      
	        // TODO: Fill in these values
	         String compartmentId = args[0];
	        String password = args[1];
 
	        AuthenticationDetailsProvider provider =
	                new ConfigFileAuthenticationDetailsProvider(configurationFilePath, profile);

	        System.out.println("sono qui : " );
	        DatabaseClient dbClient = new DatabaseClient(provider);
	        dbClient.setRegion(Region.EU_FRANKFURT_1);
	        // 
            String IdStop="<...>";
            String IdStart="<...>";
            AutonomousDatabase adw = null;
            adw =
 	                dbClient.getAutonomousDatabase(
 	                                GetAutonomousDatabaseRequest.builder()
 	                                        .autonomousDatabaseId(IdStart)
 	                                        .build())
 	                        .getAutonomousDatabase();
 	        System.out.println("GET request returned :" + adw);
            
            // Start
	        // Start
	        System.out.println("Starting Autonomous Datawarehouse Shared : " + adw);
	        if (adw.getId().equals(IdStart)) {
	        adw = waitForInstanceToBecomeAvailable(dbClient,adw.getId());
	        System.out.println("Started Autonomous Datawarehouse Shared : " + adw);

	        }
             
             System.out.println("test Autonomous Datawarehouse Shared : " + adw.getDbName());
             System.out.println("test Autonomous Datawarehouse Shared : " + adw.getDbVersion());
             System.out.println("test Autonomous Datawarehouse Shared : " + adw.getDisplayName());
             System.out.println("test Autonomous Datawarehouse Shared : " + adw.getCpuCoreCount());
             System.out.println("test Autonomous Datawarehouse Shared : " + adw.getId());
             System.out.println("test Autonomous Datawarehouse Shared : " + adw.getLifecycleDetails());
             System.out.println("test Autonomous Datawarehouse Shared : " + adw.getConnectionStrings().toString());
           
             
             // Get
 	        adw =
 	                dbClient.getAutonomousDatabase(
 	                                GetAutonomousDatabaseRequest.builder()
 	                                        .autonomousDatabaseId(adw.getId())
 	                                        .build())
 	                        .getAutonomousDatabase();
 	        System.out.println("GET request returned :" + adw);
	        dbClient.close();
	    }

I retrieve existing database information if it is stopped or started and others informations but does I can't  stop or start the database. The same for the create new database ADW.
After few minutes i receaved this error:

Inizio waitForInstanceToBecomeAvailable
Exception in thread "main" com.oracle.bmc.waiter.BmcGenericWaiter$WaitConditionFailedException: Failed to reach desired condition
    at com.oracle.bmc.waiter.BmcGenericWaiter.execute(BmcGenericWaiter.java:88)
    at com.oracle.bmc.waiter.BmcGenericWaiter$1.call(BmcGenericWaiter.java:124)
    at com.oracle.bmc.waiter.internal.SimpleWaiterImpl.execute(SimpleWaiterImpl.java:43)
    at ADW.AutonomousADW.waitForInstanceToBecomeAvailable(AutonomousADW.java:212)
    at ADW.AutonomousADW.main(AutonomousADW.java:76)

I have another issues, when start the java class I have this error for this classes:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

where I find these classes

**Comment by jodoglevy** [comment]
Hi @orcl1521,

For your first question - it seems like the when you try to start or stop an ADW, or create an ADW, it is failing to reach the desired state you are checking for. If you go to the console, does the ADW you are starting/stopping (or creating) end up reaching the right state, or does it never reach that state?

For your second question - this is related to not having configured logging for the SDK. See https://docs.cloud.oracle.com/en-us/iaas/Content/API/SDKDocs/javasdkconfig.htm#logging for more details on how to resolve that.

**Comment by orcl1521** [comment]
Hi,
for the first issue, never reach that state, but I solved it by not using "waitForInstanceToBecomeAvailable (dbClient, adw.getId ());" and I not using waiters. For the last issue, I using eclipse,  and I have add to Build Path of project the jar. But when run I have alwais the same error.

**Comment by orcl1521** [comment]
Hi,
i have the necessity to call a class that retrieve the information about the status of database into a servlet java. I create this sample class:


//import com.oracle.bmc.ConfigFileReader;
import com.oracle.bmc.Region;
//import com.oracle.bmc.ConfigFileReader.ConfigFile;
import com.oracle.bmc.auth.AuthenticationDetailsProvider;
import com.oracle.bmc.auth.ConfigFileAuthenticationDetailsProvider;
import com.oracle.bmc.database.DatabaseClient;
import com.oracle.bmc.database.model.AutonomousDatabase;
import com.oracle.bmc.database.requests.GetAutonomousDatabaseRequest;



/**
 * `getAutonomousDatabase` DBOCID
 */

public class getAutonomousDatabases {


    static String configurationFilePathGet = null; 
    

    // TODO: Fill in these values

     static String IdGet=null;
     static String profile =null;
     static Region IdRegion=null;
     static String configurationFilePath = null;
     
     public static void main(String configurationFilePathGet) {
        try {
        	
            System.out.println("\n================================\n");
            System.out.println("getAutonomousDB Information ");
          /* 
            if (args.length != 1) {
                throw new Exception(
                        "This example expects 1 argument:  A Container Database System OCID");
            }

            String configurationFilePathGet = args[0];
            */
            
        	profile=GetParameter.getprofile(configurationFilePathGet);
        	IdGet=GetParameter.getIdGet(configurationFilePathGet);
        	IdRegion=GetParameter.getIdGetRegion(configurationFilePathGet); 
        	configurationFilePath=GetParameter.getconfigurationFilePath(configurationFilePathGet); 
        	
        	
            AuthenticationDetailsProvider provider = new ConfigFileAuthenticationDetailsProvider(configurationFilePath, profile);

            System.out.println("\n================================\n");
            System.out.println("Credentials 'n such; ");
            System.out.println(provider.toString());
            
            DatabaseClient dbClient = new DatabaseClient(provider);
            dbClient.setRegion(IdRegion);

            AutonomousDatabase item = dbClient.getAutonomousDatabase(
                    GetAutonomousDatabaseRequest.builder()
                            .autonomousDatabaseId(IdGet)
                            .build())
                    .getAutonomousDatabase();

            System.out.println("\n================================");
            System.out.println("id = " + item.getId());
            System.out.println("dbName = " + item.getDbName());
            System.out.println("displayName = " + item.getDisplayName());
            System.out.println("serviceConsoleUrl = " + item.getServiceConsoleUrl());
            System.out.println("LifecycleState = " + item.getLifecycleState());
            System.out.println("\n" + item.toString());

            dbClient.close();
            
            System.out.println("\n================================");
            System.out.println("=== DONE ===");
            System.out.println("================================");

        } catch (Exception ex) {
            System.out.println("================================");
            System.out.println("=== ERROR ===");
            System.out.println("================================");

            System.out.println(ex.toString());
            ex.printStackTrace();
        }

     }
    }

    
Ths class receive the path of config file with ID, passphrase ecc.
I execute the servlet into tomcat and I have add all library to lib path of tomcat. When I call this class I have this error when call the method " DatabaseClient dbClient = new DatabaseClient(provider);".
I have this error:
================================java.lang.IllegalArgumentException: The provided passphrase is incorrect.
=== ERROR ===
================================
java.lang.IllegalArgumentException: The provided passphrase is incorrect.

	at com.oracle.bmc.http.signing.internal.PEMFileRSAPrivateKeySupplier.<init>(PEMFileRSAPrivateKeySupplier.java:97)
	at com.oracle.bmc.http.signing.internal.DefaultRequestSignerFactory.createKeySupplier(DefaultRequestSignerFactory.java:111)
	at com.oracle.bmc.http.signing.internal.DefaultRequestSignerFactory.createRequestSigner(DefaultRequestSignerFactory.java:54)
	at com.oracle.bmc.database.DatabaseClient.<init>(DatabaseClient.java:268)
	at com.oracle.bmc.database.DatabaseClient.<init>(DatabaseClient.java:219)
	at com.oracle.bmc.database.DatabaseClient.<init>(DatabaseClient.java:182)
	at com.oracle.bmc.database.DatabaseClient.<init>(DatabaseClient.java:147)
	at com.oracle.bmc.database.DatabaseClient.<init>(DatabaseClient.java:119)
	at com.oracle.bmc.database.DatabaseClient.<init>(DatabaseClient.java:94)
	at com.oracle.bmc.database.DatabaseClient.<init>(DatabaseClient.java:71)
	at com.oracle.bmc.database.DatabaseClient.<init>(DatabaseClient.java:57)
at com.oracle.bmc.database.DatabaseClient.<init>(DatabaseClient.java:46)
	at getAutonomousDatabases.main(getAutonomousDatabases.java:57)
	at GetInfoAdw.doPost(GetInfoAdw.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
..... etc

Have you any ideas? It is correct that a call oci-sdk from a java servlet/jsp?

Thanks

**Comment by jodoglevy** [comment]
Are you sure your private key passphrase that you provided (looks like in the config file) is correct?

Does the same code / config file / private key / passphrase work from outside of a Java servlet, such as from your local computer?

If you use a private key that is not encrypted with a passphrase, does it work?

**Comment by orcl1521** [comment]
Hi,
for the  question 1 and 2 yes. The question 3 I can't test it.

**Comment by jodoglevy** [comment]
Thanks. Why can't you test #3 though?

**Comment by orcl1521** [comment]
Because I do not know what to do. If you explain to me how not to use the passphrase I can try

**Comment by jodoglevy** [comment]
The directions for how to generate an API key (which includes how to generate one without a password) are here: https://docs.cloud.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm#two

**Comment by orcl1521** [comment]
Hi,
I resolved all issues.
