### ISSUE TITLE
Getting error 'Processing exception while communicating to: https://streaming.us-phoenix-1.oci.oraclecloud.com'

### ISSUE THREAD

**Issue by suraja1520** [oracle/oci-java-sdk#215]
Hi Team,
I am getting the below error when i tried to run the application using docker image. But same application i tried to run using standalone , i am able to get the messages from the stream.
Can you please help me on this?
[Error.txt](https://github.com/oracle/oci-java-sdk/files/4574922/Error.txt)

**Comment by jodoglevy** [comment]
Hi @suraja1520 - i see "java.security.cert.CertificateException: No name matching streaming.us-phoenix-1.oci.oraclecloud.com found" in your error file. Seems like an SSL error related to your docker image, if it works outside the docker image

**Comment by jodoglevy** [comment]
@suraja1520 - any update on this one? Were you able to resolve the issue in your docker image? Wondering if this can be closed

**Comment by jodoglevy** [comment]
@suraja1520 since we haven't heard from you in a while, I'm going to close this issue. If you are still experiencing this issue, please feel free to reopen this
