### ISSUE TITLE
Duplicate dependency definition in oci-java-sdk-bom

### ISSUE THREAD

**Issue by aalmiray** [oracle/oci-java-sdk#221]
Maven outputs a warning that should be easy to fix

    [WARNING] 
    [WARNING] Some problems were encountered while building the effective model for com.oracle.oci.sdk:oci-java-sdk-bom:pom:1.17.3
    [WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.oracle.oci.sdk:oci-java-sdk-resourcesearch:jar -> duplicate declaration of version 1.17.3 @ line 108, column 19
    [WARNING] 
    [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
    [WARNING] 
    [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
    [WARNING]

**Comment by y-chandra** [comment]
Thanks @aalmiray for the fix. We've merged the change.
