### ISSUE TITLE
com.oracle.bmc.database.DatabaseClient.getAutonomousDatabase: Processing exception

### ISSUE THREAD

**Issue by vikash-oracle** [oracle/oci-java-sdk#225]
Using SDK 1.17.4:

(-1, null, false) Processing exception while communicating to: https://database.eu-frankfurt-1.oraclecloud.com (outbound opc-request-id: 38FF245F5CC44D138D2703F16B237609)
com.oracle.bmc.http.internal.RestClient.convertToBmcException(RestClient.java:665)
com.oracle.bmc.http.internal.RestClient.get(RestClient.java:159)
com.oracle.bmc.database.DatabaseClient.lambda$null$90(DatabaseClient.java:1926)
com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCall(BmcGenericRetrier.java:88)
com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:59)
com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:55)
com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:50)
com.oracle.bmc.database.DatabaseClient.lambda$getAutonomousDatabase$91(DatabaseClient.java:1923)
com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCall(BmcGenericRetrier.java:88)
com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:59)
com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:55)
com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:50)
com.oracle.bmc.database.DatabaseClient.getAutonomousDatabase(DatabaseClient.java:1917)

**Comment by vikash-oracle** [comment]
Log messages before hitting Processing exception

30-May-2020 02:33:27.438 INFO [jobid-57] com.oracle.bmc.Services.create Registering new service: Services.BasicService(serviceName=DATABASE, serviceEndpointPrefix=database, serviceEndpointTemplate=https://database.{region}.{secondLevelDomain})
30-May-2020 02:33:27.465 INFO [jobid-57] com.oracle.bmc.Region.getEndpoint Loaded service 'DATABASE' endpoint mappings: {EU_FRANKFURT_1=https://database.eu-frankfurt-1.oraclecloud.com}
30-May-2020 02:33:28.017 INFO [jobid-57] com.oracle.bmc.util.JavaRuntimeUtils.<clinit> Determined JRE version as Java_8
30-May-2020 02:33:28.017 INFO [jobid-57] com.oracle.bmc.http.DefaultConfigurator.setConnectorProvider Setting connector provider to HttpUrlConnectorProvider
30-May-2020 02:33:28.322 INFO [jobid-57] com.oracle.bmc.database.DatabaseClient.setEndpoint Setting endpoint to https://database.eu-frankfurt-1.oraclecloud.com
30-May-2020 02:33:28.593 INFO [jobid-57] com.oracle.bmc.database.DatabaseClient.<init> Authentication details provider configured for region 'EU_FRANKFURT_1', but endpoint specifically set to 'https://database.eu-frankfurt-1.oraclecloud.com'. Using endpoint setting instead of region.
30-May-2020 02:33:28.593 INFO [jobid-57] com.oracle.bmc.database.DatabaseClient.setEndpoint Setting endpoint to https://database.eu-frankfurt-1.oraclecloud.com
30-May-2020 02:33:30.461 INFO [jobid-57] com.oracle.bmc.ClientRuntime.<init> Using SDK: Oracle-JavaSDK/1.17.4
30-May-2020 02:33:30.462 INFO [jobid-57] com.oracle.bmc.ClientRuntime.<init> User agent set to: Oracle-JavaSDK/1.17.4 (Linux/4.14.35-1902.10.8.el7uek.x86_64; Java/1.8.0_251; Java HotSpot(TM) 64-Bit Server VM/25.251-b02)

**Comment by vikash-oracle** [comment]
Cause of BmcException:

shaded.com.oracle.oci.javasdk.javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by mricken** [comment]
@vikash-oracle , is this the entire stack trace?

```
(-1, null, false) Processing exception while communicating to: https://database.eu-frankfurt-1.oraclecloud.com (outbound opc-request-id: 38FF245F5CC44D138D2703F16B237609)
com.oracle.bmc.http.internal.RestClient.convertToBmcException(RestClient.java:665)
com.oracle.bmc.http.internal.RestClient.get(RestClient.java:159)
com.oracle.bmc.database.DatabaseClient.lambda$null$90(DatabaseClient.java:1926)
com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCall(BmcGenericRetrier.java:88)
com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:59)
com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:55)
com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:50)
com.oracle.bmc.database.DatabaseClient.lambda$getAutonomousDatabase$91(DatabaseClient.java:1923)
com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCall(BmcGenericRetrier.java:88)
com.oracle.bmc.retrier.BmcGenericRetrier.lambda$execute$0(BmcGenericRetrier.java:59)
com.oracle.bmc.waiter.GenericWaiter.execute(GenericWaiter.java:55)
com.oracle.bmc.retrier.BmcGenericRetrier.execute(BmcGenericRetrier.java:50)
com.oracle.bmc.database.DatabaseClient.getAutonomousDatabase(DatabaseClient.java:1917)

Caused by:
shaded.com.oracle.oci.javasdk.javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by mricken** [comment]
The error message points towards a missing certificate in your Java keystore.

See, for instance, https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ

**Comment by mricken** [comment]
@vikash-oracle Is this still an issue for you?

**Comment by vikash-oracle** [comment]
@mricken Client Java property javax.net.ssl.trustStore was set incorrectly. The issue can be closed. Thank you!
