### ISSUE TITLE
UploadManager maximum retry attempts should be configurable via a system property

### ISSUE THREAD

**Issue by lovababug** [oracle/oci-java-sdk#233]
Hi,
We are using this SDK in Oracle Data Cloud Qubole to connect to OCI Casper buckets. There are few map-reduce jobs which will process data for long time and write results back to Casper bucket. 

We observed that UploadManager class has a hard coded value 3 for max attempts.  Our MR jobs are taking too long to finish if any task is failed to upload a part within 3 attempts.

We would appreciate if max-attempts can be configurable via a system property so that it can be set with -D option while launching MR job.

Thanks.

**Comment by lovababug** [comment]
Here is my proposal,

https://github.com/oracle/oci-java-sdk/pull/234 

Thank you.

**Comment by y-chandra** [comment]
Left a comment on the PR :
> Hello @lovababug,
> I don't think it would be appropriate to configure the variables via system properties in the SDK code. What I propose is, to add an optional RetryConfiguration field (that defaults to the default retry configuration) to UploadConfiguration, when creating a new instance of the UploadManager, this property can be passed wrapped within the UploadConfiguration. And in the upload method, the request's retryConfiguration can be set to this predefined property. And If you'd like to configure the variables via the system property, you can have that logic in your client code instead and pass it to the constructor.
> Please let me know your thoughts...

**Comment by y-chandra** [comment]
This feature has been added in the PR (https://github.com/oracle/oci-java-sdk/pull/245) and it has been merged...
