### ISSUE TITLE
Fetch user name from user ocid

### ISSUE THREAD

**Issue by anujkgarg** [oracle/oci-java-sdk#237]
Hello all, 

How can I fetch the user details (name, email id etc) using user OCID ? Is there any sample code available ?

Thanks,

**Comment by jodoglevy** [comment]
Hi @anujkgarg - you can use the getUser method of the IdentityClient class for this.

You can see an example of using this to get the user's name and email [here](https://github.com/oracle/oci-java-sdk/blob/master/bmc-examples/src/main/java/UserEmailExample.java#L77).

**Comment by anujkgarg** [comment]
Thanks!!
