### ISSUE TITLE
Error on requestSummarizedUsages of UsageapiClient - Passed date does not have the right precision

### ISSUE THREAD

**Issue by herberson** [oracle/oci-java-sdk#246]
When running the UsageapiClient I receive the error:

```txt
[2020-08-24 18:05:47.470] ERROR Caller+0	 at etice.oracle.cloud.Usage.main(Usage.java:78)
 (400, InvalidParameter, false) Passed date does not have the right precision (opc-request-id: 2C1C8EE4E9934367A71E93A78B747426/3D7B073C298CE10E71A52F2B9A0C581B/489FE242B760536E905F20A2EFA6D823)
com.oracle.bmc.model.BmcException: (400, InvalidParameter, false) Passed date does not have the right precision (opc-request-id: 2C1C8EE4E9934367A71E93A78B747426/3D7B073C298CE10E71A52F2B9A0C581B/489FE242B760536E905F20A2EFA6D823)
```

Bellow are the code I wrote to build the request object:

```java
final RequestSummarizedUsagesDetails details = RequestSummarizedUsagesDetails.builder()
        .compartmentDepth(new BigDecimal("6"))
        .granularity(Granularity.Daily)
        
        .timeUsageStarted(DateUtils.parseDate("2020-08-01", "yyyy-MM-dd"))
        .timeUsageEnded(DateUtils.parseDate("2020-08-25", "yyyy-MM-dd"))
                        
        .groupBy(Arrays.asList("skuPartNumber"))
        .queryType(QueryType.Cost)
        
        .tenantId(provider.getTenantId())
        
        .build();
```

The DateUtils class is from package org.apache.commons.lang3.time.

The request works with _raw request_ (https://docs.cloud.oracle.com/en-us/iaas/Content/API/Concepts/signingrequests.htm#seven).

**Comment by honniu** [comment]
For datetime format, you can follow
`Using granularity
The Usage API supports: MONTLY, DAILY, and HOURLY granularity. All startTime are inclusive, and endTime are exclusive, the same as a Java substring.

For HOURLY, only a maximum 36-hour time period is supported, with no more precision than an hour. This means no minutes or seconds in the input time.
For MONTHLY, only the first date of the month to another first date of the month is supported. For example, 2020-06-01T00:00:00Z, a maximum 12-month period.

For DAILY, no more precision than a day is supported, with a maximum 90-day period. You must enter this as 00:00:00. For example, 2020-06-01T00:00:00Z.`

For more instruction, you can check https://docs.oracle.com/en-us/iaas/Content/Billing/Concepts/costanalysisoverview.htm#cost_analysis_using_the_api. There are more explanation.

example api request:
{ "tenantId": "xxx", "timeUsageStarted": "2020-04-01T00:00:00.000Z", "timeUsageEnded": "2020-04-30T00:00:00.000Z", "granularity": "DAILY", "groupBy": ["service","skuName"], "compartmentDepth": null, "filter": null }

**Comment by jodoglevy** [comment]
@herberson given @honniu's response, were you able to resolve your issue?

**Comment by jodoglevy** [comment]
Hi @herberson - since we haven't heard back from you, I'll be resolving this issue. But feel free to reopen this if you are still experiencing problems.

**Comment by herberson** [comment]
This got time but i figured out.

Instead of "DateUtils.parseDate("2020-08-01", "yyyy-MM-dd")"  use "java.time":

LocalDate start = LocalDate.parse("2023-07-01");
Date.from(start.atStartOfDay().atZone(ZoneId.of("UTC")).toInstant())
