### ISSUE TITLE
Maven release

### ISSUE THREAD

**Issue by owainlewis** [oracle/oci-java-sdk#25]
As a user of the oci-java-sdk, I need the SDK to be available via Maven. This issue is to track the release of the SDK to Maven.

**Comment by jodoglevy** [comment]
Thanks Owain, we're working on this.

**Comment by jhult** [comment]
I created an [oracle organization on Bintray](https://bintray.com/oracle/) and created a package for [oci-java-sdk](https://bintray.com/oracle/jars/com.oracle.oci.sdk).

I also uploaded the latest version (1.2.16) and got it included in [JCenter](https://bintray.com/bintray/jcenter?filterByPkgName=com.oracle.oci.sdk).

Bintray can publish to MavenCentral: https://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/

Bintray can also GPG sign JARs automatically: https://blog.bintray.com/2013/08/06/fight-crime-with-gpg/

If someone from Oracle wants access to Bintray, feel free to [contact me](https://jonathanhult.com/blog/contact/).

**Comment by priteshkp** [comment]
Thanks, @jhult .  If Bintray is commonly used, I'm sure somebody from Oracle ( @brunoborges  ?) might be interested in taking ownership.

Also, the artifacts that you uploaded, are they the ones that were downloaded from the releases here or did you manually build them?  Thanks.
Pritesh

**Comment by brunoborges** [comment]
Hi @jhult, thanks for taking the first step. Yes I'd be happy to take ownership and bring that account to under our umbrella. My email is bruno.borges@oracle.com. Can you please do the transfer?

**Comment by jhult** [comment]
The artifacts I uploaded to Bintray were downloaded from the Github releases. I did not manually build them. 

Ownership of the oracle organization has been transferred. I'd recommend adding a few additional Oracle people.

I'd recommend the following next steps:
* [setup GPG signing](https://bintray.com/docs/usermanual/interacting/interacting_bintrayorganizations.html#_gpg_signing_for_bintray_organizations)
* [setup a Sonatype account](http://central.sonatype.org/pages/ossrh-guide.html) so you can auto publish from Bintray to Maven Central

**Comment by eginez** [comment]
hey @brunoborges Could you add me, @jodoglevy and @mricken to the bintray account?

**Comment by brunoborges** [comment]
Yeap, let's chat about that. I will close this ticket while we discuss our release process.

Thanks @jhult for pushing us forward :-)

**Comment by jhult** [comment]
@brunoborges and @eginez,

Any updates on this? It looks like the original <i>oci-java-sdk</i> package I uploaded has disappeared.

Does Oracle plan to push releases to Bintray / MavenCentral?

**Comment by jodoglevy** [comment]
We're still working on Maven support using Bintray. Requires some approvals on our end. Reopening.

**Comment by jhult** [comment]
@tmiddlet2666, may be able to help as they appear to have done this already with this project: https://github.com/oracle/accs-caching-java-sdk/

**Comment by jodoglevy** [comment]
@jhult thanks, where are you seeing https://github.com/oracle/accs-caching-java-sdk/ on Bintray? I can tell from the readme its on Maven, but not Bintray (as the way its getting on Maven) specifically.

**Comment by jhult** [comment]
I think I was referencing that they have deployed to [Maven Central](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.oracle.cloud.caching%22) before (not necessarily Bintray).

The artifact is on Bintray [here](https://bintray.com/bintray/jcenter/com.oracle.cloud.caching%3Acache-client-api) (but it only appears to be there as part of JCenter which is a superset of Maven Central).

**Comment by dansmithy** [comment]
Here is a way to use the SDK from Maven until it is in a public Maven repository. It involves building and committing the SDK JARs to your project repository, but avoids committing the third party dependencies that *are* found in a public Maven repository.

1. Clone the Java SDK source.
1. Create a /repo directory inside the source.
1. Run `mvn deploy -DaltDeploymentRepository=localStagingDir::default::file://repo` to populate the /repo directory with the OCI SDK JARs arranged in a Maven repository format, complete with metadata.
1. Put the contents of /repo in YOUR project.
1. Use this POM file for YOUR project (this references just the object storage JAR, but you can reference others):

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    ...
    
    <repositories>
        <repository>
            <id>localrepo</id>
            <url>file://${project.basedir}/repo</url>
        </repository>
    </repositories>

    <dependencies>

        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-objectstorage</artifactId>
            <version>1.2.29</version>
        </dependency>

        ...
        
    </dependencies>

    ...

</project>
```

**Comment by galvinograd** [comment]
+1
I need a way to install this artifact, I don't want to get back to the git sub-modules days. Do you have an ETA?

**Comment by jodoglevy** [comment]
No ETA at this time, but we're making progress

**Comment by menih** [comment]
Need it also.

**Comment by alan-parry** [comment]
another +1 here please

**Comment by gavares** [comment]
Any status update on this?

**Comment by jodoglevy** [comment]
We are currently in the final stages of approval for using Bintray to get on Maven. Stay tuned!

**Comment by jhult** [comment]
@jodoglevy, any updates?

**Comment by aunayak** [comment]
+1 here, @dipeen-oracle

**Comment by jodoglevy** [comment]
Still working on legal / compliance approvals, sorry for the delay.

**Comment by ljnelson** [comment]
Any updates to this issue?

**Comment by jodoglevy** [comment]
Still working on legal / compliance approvals

**Comment by yiwawang2017** [comment]
I suppose this is obvious but still want to point out. One of the important reasons to have oci-java-sdk maven release is to allow oci-java-sdk consumers to use oci-java-sdk as maven dependency for java Maven/Gradle projects.

We used to use was-java-sdk, and it has excellent maven support (maven modules with well defined dependencies (including 3rdparty dependencies), which made available from public maven repository: 
http://central.maven.org/maven2/com/amazonaws/

I assume oci-java-sdk maven release will be similar regardless which maven repository to use.

**Comment by jodoglevy** [comment]
We now have approval to use Bintray to get the Java SDK onto Maven, and so should have an update here shortly!

**Comment by suman-ganta** [comment]
any update?

**Comment by jodoglevy** [comment]
We are currently testing deployments to Bintray. Stay tuned!

**Comment by eginez** [comment]
All we have a version of the java-sdk released in maven. The *only* avaliable version currently is 1.5.2
https://search.maven.org/search?q=com.oracle.oci.sdk

If you are have been waiting to consume the java sdk from maven central. Please update your pom file to point to the public artifacts and let us know if you are running into any issues.

Caveat: The published version does not java `oci-java-sdk-full` thus if want to include all java-sdk packages, you'll have to include them individually. We are working on fixing that issue.
For now you can use the https://github.com/oracle/oci-java-sdk/blob/master/bmc-examples/pom.xml as an example on how to include different java-sdk packages in your pom file

**Comment by owainlewis** [comment]
Great news. Thanks @eginez 👍

**Comment by eginez** [comment]
All 
I am happy to let you know that we have and will continue to push all of our java releases to public maven repositories.
Feel free to depend on the java sdk via your favorite build tool. For more info on the setup, see: https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/javasdkgettingstarted.htm
