### ISSUE TITLE
Get the cause of failure when MultiPartAssembler fails in OCI OS

### ISSUE THREAD

**Issue by akshaysu** [oracle/oci-java-sdk#264]
With the current version(1.25.0) there is no way to get a reason for the failure of individual parts. Although there is a way to get which parts got failed through Manifest but no way to get the error message of BMCExcpetion.

When the commit is called on MultiPartAssembler it throws IllegalStateException with a message "One or more parts were have not completed the upload successfully"
It will be very useful to get the cause of the exact failure.

Please refer https://stackoverflow.com/questions/64515404/reason-for-failure-in-multipartobjectassembler-oci-object-storage

**Comment by y-chandra** [comment]
Java SDK (v1.27.1) has been added with the feature to get a list of failed parts along with the Exception that caused the parts to fail.
`MultipartManifest` now exposes the function `MultipartManifest.listFailedPartsDetails()` which returns a list of [MultipartUploadFailedPartDetails](https://github.com/oracle/oci-java-sdk/blob/master/bmc-objectstorage/bmc-objectstorage-extensions/src/main/java/com/oracle/bmc/objectstorage/transfer/internal/MultipartUploadFailedPartDetails.java), which comprises of the part number and the failureCause.

Please check the below link for reference :
https://github.com/oracle/oci-java-sdk/blob/fe31ae3faf984dee65856d18047b45e36fbfd8e5/bmc-objectstorage/bmc-objectstorage-extensions/src/test/java/com/oracle/bmc/objectstorage/transfer/MultipartObjectAssemblerTest.java#L466

**Comment by y-chandra** [comment]
Closing this, since the feature has been implemented.
