### ISSUE TITLE
ObjectStorageGetNamespaceExample.java (errormessage shows CompartmentID instead of TenantID)

### ISSUE THREAD

**Issue by ogroef** [oracle/oci-java-sdk#270]
When I run the "ObjectStorageGetNamespaceExample.java"-example and I provide a compartmentId.

The following error message is shown: `"main" com.oracle.bmc.model.BmcException: (404, CompartmentIdNotFound, false) Either the Tenant with TenantID 'ocid1.compartment.oc1..aaaaaaaa6uy7pooqik2kdp3isnymj...' does not exist  or you are not authorized to access it (...).`

Is it normal that the "OCID" shown in the error message points to the compartmentId and not the TenantID?

When I use the same config-file in "ObjectStorageAsyncExample.java".  I can show all buckets in the compartment, and namespace is fetched successfully.

Regards
Olivier

**Comment by jodoglevy** [comment]
Hi @ogroef 

For this code in the ObjectStorageGetNamespaceExample example, what value are you passing as the compartment id?

```
        GetNamespaceRequest getNamespaceRequest =
                GetNamespaceRequest.builder().compartmentId(compartmentId).build();
        String namespace = objectStorageClient.getNamespace(getNamespaceRequest).getValue();
```

As you can see in the ObjectStorageAsyncExample example, this example does not pass a compartment id to the GetNamespace operation:

`client.getNamespace(GetNamespaceRequest.builder().build(), namespaceHandler);`

This is why one of the examples is working for you and one is not -- only the former example passes in a compartment id to the GetNamespace operation, the latter does not. The compartment id you are passing in, as the error message states, either "does not exist or you are not authorized to access it".

**Comment by jodoglevy** [comment]
Hi @ogroef . Are you still running into issues? Or can this be closed?

**Comment by jodoglevy** [comment]
@ogroef since we haven't heard from you in a while, I'll be closing this issue. Please feel free to reopen it if you are still experiencing this issue
