### ISSUE TITLE
Region Support

### ISSUE THREAD

**Issue by sachinjain3677** [oracle/oci-java-sdk#273]
Hi, I am an employee at Oracle IDC. As I understand this SDK doesn't yet support all the regions on Oracle Cloud. Is there an alternate internal way to test my code on AP_MUMBAI_1 region ? I need it for some development in OAC.

**Comment by jodoglevy** [comment]
Hi @sachinjain3677 - for internal questions, you should reach out internally, not externally via GitHub. That said, this does not appear to be an internal question. Mumbai (and all other public OCI regions) are supported in the OCI SDKs. You can see so in the SDK code on GitHub [here](https://github.com/oracle/oci-java-sdk/blob/cefd90c015e38e6f0dbcebe6739ba4184b6af7a7/bmc-common/src/main/java/com/oracle/bmc/Region.java#L83).

Please let me know if this issue can be closed.

**Comment by jodoglevy** [comment]
Closing this issue as I haven't heard from you @sachinjain3677, and your question should be answered at this point. But please let me know if you are still facing issues

**Comment by sachinjain3677** [comment]
Hi @jodoglevy, sorry I got busy somewhere forgot about this completely, yes please close the issue. Thanks.
