### ISSUE TITLE
Anonymous access to Object Storage

### ISSUE THREAD

**Issue by aalmiray** [oracle/oci-java-sdk#276]
Is there an example/docs on how to configure anonymous read access to an ObjectStorage bucket?

**Comment by hadiyarajesh** [comment]
You need to create pre-authorized requests to allow anonymous access

Here's how you can do that on object (similar for bucket)

`val preAuthenticatedRequestDetails = CreatePreauthenticatedRequestDetails.builder()
        .objectName("object_name")
        .name("my_pre_authenticated_request")
        .timeExpires(Date.from(Instant.now().plus(30, ChronoUnit.MINUTES)))
        .accessType(CreatePreauthenticatedRequestDetails.AccessType.ObjectRead)
        .build()

    val preAuthenticatedRequest = CreatePreauthenticatedRequestRequest.builder()
        .namespaceName("namespace_name")
        .bucketName("bucket_name")
        .createPreauthenticatedRequestDetails(preAuthenticatedRequestDetails)
        .build()

    val response = client.createPreauthenticatedRequest(preAuthenticatedRequest)
    println(response.preauthenticatedRequest.accessUri)`

**Comment by hadiyarajesh** [comment]
You need to create pre-authorized requests to allow anonymous access

Here's how you can do that on object (similar for bucket)

`
val preAuthenticatedRequestDetails = CreatePreauthenticatedRequestDetails.builder()
        .objectName("object_name")
        .name("my_pre_authenticated_request")
        .timeExpires(Date.from(Instant.now().plus(30, ChronoUnit.MINUTES)))
        .accessType(CreatePreauthenticatedRequestDetails.AccessType.ObjectRead)
        .build()

    val preAuthenticatedRequest = CreatePreauthenticatedRequestRequest.builder()
        .namespaceName("namespace_name")
        .bucketName("bucket_name")
        .createPreauthenticatedRequestDetails(preAuthenticatedRequestDetails)
        .build()

    val response = client.createPreauthenticatedRequest(preAuthenticatedRequest)
    println(response.preauthenticatedRequest.accessUri)`

**Comment by hadiyarajesh** [comment]
You need to create pre-authorized requests to allow anonymous access

Here's how you can do that on object (similar for bucket)

  `val preAuthenticatedRequestDetails = CreatePreauthenticatedRequestDetails.builder()
          .objectName("object_name")
          .name("my_pre_authenticated_request")
          .timeExpires(Date.from(Instant.now().plus(30, ChronoUnit.MINUTES)))
          .accessType(CreatePreauthenticatedRequestDetails.AccessType.ObjectRead)
          .build()

    val preAuthenticatedRequest = CreatePreauthenticatedRequestRequest.builder()
        .namespaceName("namespace_name")
        .bucketName("bucket_name")
        .createPreauthenticatedRequestDetails(preAuthenticatedRequestDetails)
        .build()

    val response = client.createPreauthenticatedRequest(preAuthenticatedRequest)
    println(response.preauthenticatedRequest.accessUri)`

**Comment by hadiyarajesh** [comment]
You need to create pre-authorized requests to allow anonymous access

Here's how you can do that on object (similar for bucket)

  `
  val preAuthenticatedRequestDetails = CreatePreauthenticatedRequestDetails.builder()
            .objectName("object_name")
            .name("my_pre_authenticated_request")
            .timeExpires(Date.from(Instant.now().plus(30, ChronoUnit.MINUTES)))
            .accessType(CreatePreauthenticatedRequestDetails.AccessType.ObjectRead)
            .build()

    val preAuthenticatedRequest = CreatePreauthenticatedRequestRequest.builder()
        .namespaceName("namespace_name")
        .bucketName("bucket_name")
        .createPreauthenticatedRequestDetails(preAuthenticatedRequestDetails)
        .build()

    val response = client.createPreauthenticatedRequest(preAuthenticatedRequest)
    println(response.preauthenticatedRequest.accessUri)`

**Comment by hadiyarajesh** [comment]
You need to create pre-authorized requests to allow anonymous access

Here's how you can do that on object in kotlin (similar for bucket)

```
  val client = ObjectStorageClient(YourOciAuthProvider())
  vat preAuthenticatedRequestDetails = CreatePreauthenticatedRequestDetails.builder()
            .objectName("object_name")
            .name("my_pre_authenticated_request")
            .timeExpires(Date.from(Instant.now().plus(30, ChronoUnit.MINUTES)))
            .accessType(CreatePreauthenticatedRequestDetails.AccessType.ObjectRead)
            .build()

    val preAuthenticatedRequest = CreatePreauthenticatedRequestRequest.builder()
        .namespaceName("namespace_name")
        .bucketName("bucket_name")
        .createPreauthenticatedRequestDetails(preAuthenticatedRequestDetails)
        .build()

    val response = client.createPreauthenticatedRequest(preAuthenticatedRequest)
    println(response.preauthenticatedRequest.accessUri)
```

**Comment by aalmiray** [comment]
I see. Well I was hoping there was a way to create a `client` in stance without a given authorization provider. The use case I have in mind requires read access without any login configuration. Could it be done perhaps using the S3 compatibility layer?

**Comment by hadiyarajesh** [comment]
I don't have much idea about S3 layer, but ultimately you need some sort of authentication so server verify identity and grant read access. Later, we can use that read only links to others but for first time, you need to authenticate, it could be your server-side code.

**Comment by aalmiray** [comment]
That's what I was afraid of, but that's alright. Thanks!
