### ISSUE TITLE
GetObjectRequest, can't fetch the body of the response

### ISSUE THREAD

**Issue by sachinjain3677** [oracle/oci-java-sdk#279]
I am trying to fetch a csv file from the object storage service using [this](https://docs.oracle.com/en-us/iaas/tools/java-sdk-examples/1.30.1/objectstorage/GetObjectExample.java.html) example.

But I am not sure how to fetch the object instance from the obtained GetObjectResponse at the end. I couldn't find any method to do the same in this [documentation](https://docs.oracle.com/en-us/iaas/tools/java/1.30.0/). Am I missing something obvious? Please help!

**Comment by VidhiBhansali** [comment]
> I am trying to fetch a csv file from the object storage service using [this](https://docs.oracle.com/en-us/iaas/tools/java-sdk-examples/1.30.1/objectstorage/GetObjectExample.java.html) example.
> 
> But I am not sure how to fetch the object instance from the obtained GetObjectResponse at the end. I couldn't find any method to do the same in this [documentation](https://docs.oracle.com/en-us/iaas/tools/java/1.30.0/). Am I missing something obvious? Please help!

@sachinjain3677 The [UploadObjectExample](https://github.com/oracle/oci-java-sdk/blob/master/bmc-examples/src/main/java/UploadObjectExample.java) shows how to fetch the object that was uploaded. Can you please refer this example and see if that helps?

**Comment by sachinjain3677** [comment]
@VidhiBhansali thanks! that was definitely helpful.
