### ISSUE TITLE
Provide a constructor in WrappedByteArrayInputStream which accepts offset and length

### ISSUE THREAD

**Issue by akshaysu** [oracle/oci-java-sdk#293]
Can you please add a new constructor which takes byte[], offset, and length. Similar to ByteArrayInputStream?

public WrappedByteArrayInputStream(byte[] buf,
                            int offset,
                            int length)

I need to construct WrappedByteArrayInputStream from byte[] with offset and length.

**Comment by omkar07** [comment]
Hi @akshaysu , thanks for filing this ticket. We are working on this issue.

**Comment by omkar07** [comment]
Hi @akshaysu , We have added the constructor which accepts offset & length in WrappedByteArrayInputStream and is available in version (1.36.1) . Hence, closing this issue since the ask is complete. Please, feel free to reopen in case of any concerns. Thanks!

**Comment by akshaysu** [comment]
Hi @omkar07, Yes I could see a new constructor as requested by me. But can I directly use WrappedByteArrayInputStream?
It is in bmc.io.internal.WrappedByteArrayInputStream. Is it safe to use this class directly from my application without worrying about future changes?

**Comment by omkar07** [comment]
Hi @akshaysu , I'm not sure what you're trying to achieve here. To help you understand, WrappedByteArrayInputStream is the wrapper over ByteArrayInputStream that allows you copy the the duplicate stream from the same underlying buffer whereas StreamUtils is a utility class that provides helper methods to work with streams. I don't see this class getting changed much. Also, what future changes are you referring to?
