### ISSUE TITLE
GPG key cannot be verified

### ISSUE THREAD

**Issue by fabianfrz** [oracle/oci-java-sdk#303]
We need the GPG key to verify the artifact we get from maven central. Without it, the signature is worthless.

The common way to provide GPG public keys is by putting it on the public keyservers which I would prefer.
Another option that is possible is via an importable ASC file which contains the public key.

**Comment by omkar07** [comment]
hey @fabianfrz , we have the CPG public key on the public keyservers and you could access it with below url. Please let us know if we are good to close this issue. thanks!
https://keys.openpgp.org/search?q=A8FF%C2%A0348E%C2%A0719E%C2%A0471F%C2%A0B758%C2%A0%C2%A0DE55%C2%A003A6%C2%A044A1%C2%A01574%C2%A04204

**Comment by fabianfrz** [comment]
@omkar07 I had to add it by hand to the build server since it was not able to find it by itself but it seems to be working with the maven pgp verify plugin. Thanks.

**Comment by pzygielo** [comment]
> we have the CPG public key on the public keyservers and you could access it with below url. Please let us know if we are good to close this issue. thanks! https://keys.openpgp.org/search?q=A8FF%C2%A0348E%C2%A0719E%C2%A0471F%C2%A0B758%C2%A0%C2%A0DE55%C2%A003A6%C2%A044A1%C2%A01574%C2%A04204

It's 404 now.

```
$ gpg --keyserver keyserver.ubuntu.com --recv-keys A8FF348E719E471FB758DE5503A644A115744204
gpg: keyserver receive failed: No data
$ gpg --keyserver keys.openpgp.org --recv-keys A8FF348E719E471FB758DE5503A644A115744204
gpg: keyserver receive failed: No data
$ gpg --keyserver pgp.mit.edu --recv-keys A8FF348E719E471FB758DE5503A644A115744204
gpg: keyserver receive failed: No data
```

Where this key could be found today?
