### ISSUE TITLE
objectstorage  - bucket put request exception using java sdk 

### ISSUE THREAD

**Issue by btcdevops-apps** [oracle/oci-java-sdk#340]
I've used different snippets of code to put an object in an oci bucket. and I've encountered a series of exceptions.
latest: (-1, null, false) Processing exception while communicating to: https://objectstorage.uk-london-1.oraclecloud.com

others:
com.oracle.bmc.model.BmcException: (401, Unknown, false) Detailed exception information not available (opc-request-id: lhr-1:AQNAxSR-EUmBqpXxNkGMmoJvYB_bkt_Y8IsLv_PlT3bw6mXqNxJAm0r5vpYUVXeJ)

My application is a rest based one using helidon mp and I have adapted the resteasy example [here](https://github.com/oracle/oci-java-sdk/blob/master/bmc-examples/src/main/java/ResteasyClientWithObjectStorageExample.java) and excluded the resteasy specific lines.

`<dependency>
    <groupId>io.helidon.integrations.cdi</groupId>
    <artifactId>helidon-integrations-cdi-oci-objectstorage</artifactId>
</dependency>`

**Comment by jodoglevy** [comment]
@btcdevops-apps i'm closing this since we haven't heard back from you in over a month - please feel free to reopen if you are still hitting this issue
