### ISSUE TITLE
Support for OAuth authentication in the Rest API 

### ISSUE THREAD

**Issue by dipeen-oracle** [oracle/oci-java-sdk#35]
Hi,
We are looking for something like OAuth, via which we can login to OCI in JAVA sdk.
Please let me know in case of any reference to APIs.

**Comment by nathan-vu** [comment]
Hi,

Currently there is no OAuth authentication available. The only authentication methods available are:

* Using an API key: https://docs.us-phoenix-1.oraclecloud.com/Content/Identity/Concepts/usercredentials.htm#two
* Using instance principals/calling services from an instance as described here: https://docs.us-phoenix-1.oraclecloud.com/Content/Identity/Tasks/callingservicesfrominstances.htm

**Comment by dipeen-oracle** [comment]
But when I login to web via link: login.us-phoenix-1.oraclecloud.com
It shows oauth2 in url !!!
something like
https://login.us-phoenix-1.oraclecloud.com/v1/oauth2/authorize?action=login..................

**Comment by nathan-vu** [comment]
Sorry for the confusion - federated identity is available via the *console* (https://docs.us-phoenix-1.oraclecloud.com/Content/Identity/Concepts/federation.htm) but if you are looking for authenticating against the APIs here: https://docs.us-phoenix-1.oraclecloud.com/Content/API/Concepts/apiref.htm (apart from the S3 compatibility API, which uses AWS-like authentication via access keys and secret keys) then the only supported ways are using an API key or instance principals, as per the link in my previous comment

**Comment by nathan-vu** [comment]
As an update, a backlog item has been logged with our Identity team to consider adding support for OAuth authentication support to the API. If it becomes a supported mechanism then we can look at adding support to the SDKs for this.

I'll leave this issue here in case different customers have the same question or wish to chime in on their need for this feature.

**Comment by msleeman** [comment]
After more careful consideration the product team is not going to consider supporting OAuth for its SDK and CLI.  The reason is that for running scripts and the Command Line using our signing spec is a better and more secure authentication than OAuth.  OAuth is good, but it relies on bearer tokens, which cannot express intent to call a particular API.  If in future we get a lot of request to support third party software calling into OCI then we will reconsider.

**Comment by cdockter** [comment]
I'm not really sure I understand the push back here.  The `scope` claim in OAuth is intended exactly for the purpose of restricting the APIs the token bearer is permitted to invoke.

Is there some other offering that allows API interactions via federated auth?

**Comment by jodoglevy** [comment]
@msleeman  can you please respond here?

**Comment by cdockter** [comment]
Any update on this issue?

**Comment by MartinSleeman** [comment]
Our team prefers the current signing authentication method for the API.  So we have no plans to support OAuth access for SDK/API.  (See above for that reasoning).  The scopes suggestion won't scale to our needs and we have no plans to support OAuth as a mechanism to access the SDK/CLI.  

However, we do have some upcoming feature that will give Federated users access to the SDK and Command line.   Is the core of your question getting access to the SDK/CLI as a federated user?

**Comment by jodoglevy** [comment]
Any other followup needed here @cdockter @dipeen-oracle ? Looks like the Identity team considers this "won't fix"

I'm going to close this shortly if I don't hear any additional pushback.

**Comment by cdockter** [comment]
I read the above response as "we don't want to and we don't care".  If there was federated auth support for API access that might help but it is unclear what authN mechanism would be used.

**Comment by MartinSleeman** [comment]
Hey CDockter, 

I'm happy to tell you that federated Auth support for [IDCS shipped recently](https://blogs.oracle.com/cloud-infrastructure/idcs-users-can-now-use-the-oracle-cloud-infrastructure-sdk-and-cli).  So if you are using IDCS you can use the API with that federated user.  We also intend to support more IDPs in the near future.  

It'd be helpful if you could expand on your use case a bit.  Is the case for an interactive user who wants to run scripts through the Java SDK?  Is it a long running process or application that's running scripts with the Java SDK?  Any more info would be helpful.  

Thx
-Martin

**Comment by cdockter** [comment]
I think you missed the point here somewhat; I don't wanted federated "users", I want federated Auth.

The issue with the current offering is I still must provision API keys for every user I want to be able to access OCI recourse. Instead, I want to be able to auth against an external authority using its native mechanism and then present proof of that auth to OCI.  

This is the basic workflow described in [RFS-6749 Section-1.2](https://tools.ietf.org/html/rfc6749#section-1.2).  With OCI acting as the **Resource Sever**, this workflow would require a trust relationship between OCI and my federated **Authority**.

I understand if this doesn't fit in your current road map but the current `IDCS` is not very useful to me or I would guess most of the people interested in this issue.

**Comment by MartinSleeman** [comment]
Thanks for the clarification of the scenario.  While we don’t have OAuth 2.0 support currently, we understand the importance of it for our ISV partners.  

We want to build a vibrant ecosystem that allows ISVs to call into the OCI SDK from their apps (web, mobile etc).  We do plan to support OAuth 2.0 eventually, but unfortunately we don’t have a short term plan to support it.  Stay tuned for updates later in 2019 as we build out or ISV ecosystem..

**Comment by andy-miles** [comment]
I'm closing this issue.  If you have any additional comments/questions, please reopen.

**Comment by KartikShrikantHegde** [comment]
Hi @cdockter and @dipeen-oracle , please let us know if you had a chance to look at the above message and try it. If not I will close this ticket soon. Thanks.

**Comment by KartikShrikantHegde** [comment]
@cdockter and @dipeen-oracle, Closing this ticket for now. Please feel free to re-open if you have questions. Thanks.

**Comment by Ordiel** [comment]
I think the ask was simple enough, developers require an implementation of `AuthenticationDetailsProvider` they can use to configure the SDK using an OAuth token. As of now the SDK is shipped with:

![image](https://github.com/oracle/oci-java-sdk/assets/9622612/a115ae58-6d32-44ef-8f0f-1019e6ce7bb6)

meaning that if I have a bearer token obtained from: `https://idcs-mydomain.idcs.identity.us-phoenix-1.oci.oraclecloud.com:443/oauth2/v1/token/` and I want to use if to create OCI SDK Clients (lets say java) there should be an: `OAut2AuthenticationDetailsProvider` (or the like) for me to use when creating a client
