### ISSUE TITLE
There is a problem creating the IdentityClient.

### ISSUE THREAD

**Issue by develiberta** [oracle/oci-java-sdk#350]
[Error Log]
java.lang.NoClassDefFoundError: Could not initialize class com.oracle.bmc.http.internal.RestClientFactoryBuilder
	at com.oracle.bmc.identity.IdentityClient.<init>(IdentityClient.java:229) ~[oci-java-sdk-identity-2.11.1.jar:na]
	at com.oracle.bmc.identity.IdentityClient.<init>(IdentityClient.java:183) ~[oci-java-sdk-identity-2.11.1.jar:na]
	at com.oracle.bmc.identity.IdentityClient.<init>(IdentityClient.java:148) ~[oci-java-sdk-identity-2.11.1.jar:na]
	at com.oracle.bmc.identity.IdentityClient.<init>(IdentityClient.java:120) ~[oci-java-sdk-identity-2.11.1.jar:na]
	at com.oracle.bmc.identity.IdentityClient.<init>(IdentityClient.java:95) ~[oci-java-sdk-identity-2.11.1.jar:na]
	at com.oracle.bmc.identity.IdentityClient.<init>(IdentityClient.java:72) ~[oci-java-sdk-identity-2.11.1.jar:na]
	at com.oracle.bmc.identity.IdentityClient.<init>(IdentityClient.java:58) ~[oci-java-sdk-identity-2.11.1.jar:na]

[Request]
identityClient = new IdentityClient(provider, config);
// provider is an instance of AuthenticationDetailsProvider and config is an instance of ClientConfiguration

**Comment by develiberta** [comment]
[Maven Dependencies]

<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.oracle.oci.sdk</groupId>
				<artifactId>oci-java-sdk-bom</artifactId>
				<version>2.11.1</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<repositories>
		<repository>
            <id>oracle</id>
            <name>ORACLE JDBC Repository</name>
            <url>http://maven.jahia.org/maven2</url>
        </repository>
   </repositories>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        
        <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>

		<dependency>
		    <groupId>org.glassfish.jersey.core</groupId>
		    <artifactId>jersey-client</artifactId>
		    <version>2.27</version>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.9.2</version>
			
             
			<exclusions> 
			    <exclusion>
			        <groupId>io.swagger</groupId>
			        <artifactId>swagger-annotations</artifactId>
			    </exclusion> 
			    <exclusion> 
			        <groupId>io.swagger</groupId> 
			        <artifactId>swagger-models</artifactId> 
			    </exclusion> 
			</exclusions>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.9.2</version>
		</dependency>
		
		 
		<dependency> 
		    <groupId>io.swagger</groupId> 
		    <artifactId>swagger-annotations</artifactId> 
		    <version>1.5.21</version> 
		</dependency> 
		
         
		<dependency> 
		    <groupId>io.swagger</groupId> 
		    <artifactId>swagger-models</artifactId> 
		    <version>1.5.21</version>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
		  <groupId>org.modelmapper</groupId>
		  <artifactId>modelmapper</artifactId>
		  <version>2.3.6</version>
		</dependency>
  
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-audit</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-common</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-core</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-database</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-dns</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-email</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-filestorage</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-identity</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-loadbalancer</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-objectstorage</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-containerengine</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-resourcesearch</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-keymanagement</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-announcementsservice</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-healthchecks</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-waas</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-streaming</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-monitoring</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-resourcemanager</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-autoscaling</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-ons</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-budget</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-workrequests</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-limits</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-functions</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-events</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-dts</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-oce</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-oda</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-analytics</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-integration</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-osmanagement</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-marketplace</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-apigateway</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-applicationmigration</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-datacatalog</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-dataflow</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-datascience</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-nosql</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-mysql</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-usageapi</artifactId>
		</dependency>
		<dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-computeinstanceagent</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-managementagent</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-databasemanagement</artifactId>
        </dependency>
		<dependency>
			<groupId>com.oracle.oci.sdk</groupId>
			<artifactId>oci-java-sdk-bastion</artifactId>
		</dependency>
           
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
		</dependency>
		
		<dependency>
		    <groupId>org.postgresql</groupId>
		    <artifactId>postgresql</artifactId>
		</dependency>	    

		
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<version>4.4.10</version>
		</dependency>

		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.6</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore-nio</artifactId>
			<version>4.4.10</version>
		</dependency>

		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpasyncclient</artifactId>
			<version>4.1.4</version>
		</dependency>

		<dependency>
		    <groupId>org.apache.httpcomponents</groupId>
		    <artifactId>httpmime</artifactId>
		    <version>4.5.6</version>
		</dependency>
		
		
		<dependency> 
			<groupId>com.oracle</groupId> 
			<artifactId>ojdbc7</artifactId> 
			<version>12.1.0.2</version> 
		</dependency>

		<dependency>
			<groupId>org.mybatis</groupId>
			<artifactId>mybatis</artifactId>
			<version>3.4.0</version>
		</dependency>

		<dependency>
			<groupId>org.mybatis</groupId>
			<artifactId>mybatis-spring</artifactId>
			<version>1.3.0</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-pool2</artifactId>
		</dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
            <version>4.4</version>
        </dependency>
		
        <dependency>
	        <groupId>com.hazelcast</groupId>
	        <artifactId>hazelcast</artifactId>
        </dependency>
		
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>

    </dependencies>

**Comment by jodoglevy** [comment]
Thanks, we'll take a look and get back

**Comment by y-chandra** [comment]
@develiberta - It doesn't seem like you're importing the java-sdk-bom in the right way. Could you please refer to [this](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/javasdkgettingstarted.htm#ariaid-title7) on how to define the `dependencyManagement` section when using `java-sdk-bom`? If the problem still persists, you can define the dependencies directly by just importing the dependencies and mentioning the versions like :
```
<dependencies>
    <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-identity</artifactId>
            <version>2.12.0</version>
    </dependency>
    <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-common</artifactId>
            <version>2.12.0</version>
    </dependency>
</dependencies>
```

**Comment by develiberta** [comment]
@y-chandra I can directly check the library files I am currently using through maven. As a result of checking directly, it was confirmed that all of them were jar files of the same version. In other words, there seems to be no problem with the way the library is imported.

**Comment by y-chandra** [comment]
As you can see, that the source code contains the class [RestClientFactoryBuilder](https://github.com/oracle/oci-java-sdk/blob/master/bmc-common/src/main/java/com/oracle/bmc/http/internal/RestClientFactoryBuilder.java)
Which means that the libraries are not being imported correctly in the project. Please follow the above comment to define the library imports correctly.

**Comment by y-chandra** [comment]
Please let us know if you were unable to resolve the error. We'll be closing this issue if we don't hear back from you in a week.

**Comment by y-chandra** [comment]
@develiberta - Closing this issue since we didn't hear back from you in a week, please feel free to re-open the issue.
