### ISSUE TITLE
ApacheConnectionClosingStrategy is missing with Gradle

### ISSUE THREAD

**Issue by fahmydiab** [oracle/oci-java-sdk#352]
I got this error while trying to use OCI in spring boot application:

NoClassDefFoundError: org/glassfish/jersey/apache/connector/ApacheConnectionClosingStrategy

I'm using :
    implementation group: 'com.oracle.oci.sdk', name: 'oci-java-sdk-bom', version: '2.12.0', ext: 'pom'

**Comment by fahmydiab** [comment]
tried implementation group: 'com.oracle.oci.sdk', name: 'oci-java-sdk-bom', version: '2.12.0' but didn't work either

**Comment by VidhiBhansali** [comment]
@fahmydiab `NoClassDefFoundError ` ususally occurs due to multiple versions of the OCI SDK library present in the project. If you are still seeing this issue, can you please check if any of the other dependencies in your project are pointing to an older version of oci-java-sdk-bom package? You can do so running `mvn dependency:tree`

**Comment by fahmydiab** [comment]
i used one version of OCI SDK, and I am using gradle

**Comment by fahmydiab** [comment]
i used OCI SDK in two projects , in the first one i had to add these libraries:

    implementation group: 'org.bouncycastle', name: 'bcprov-jdk15on', version: '1.68'

    implementation group: 'com.oracle.oci.sdk', name: 'oci-java-sdk-objectstorage', version: '2.12.0'

    implementation group: 'org.glassfish.jersey.core', name: 'jersey-common', version: '2.34'
    implementation group: 'org.glassfish.jersey.core', name: 'jersey-client', version: '2.34'
    implementation group: 'org.glassfish.jersey.connectors', name: 'jersey-apache-connector', version: '2.34'
    implementation group: 'org.glassfish.jersey.inject', name: 'jersey-hk2', version: '2.34'

**Comment by fahmydiab** [comment]
in the second one i used : 
implementation group: 'com.oracle.oci.sdk', name: 'oci-java-sdk-objectstorage', version: '2.12.0'

    implementation group: 'org.bouncycastle', name: 'bcprov-jdk15on', version: '1.68'

    implementation group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.13'
    implementation group: 'org.apache.httpcomponents', name: 'httpcore', version: '4.4.13'

    implementation group: 'org.glassfish.jersey', name: 'jersey-bom', version: '2.34', ext: 'pom'
    implementation group: 'org.glassfish.jersey.core', name: 'jersey-common', version: '2.34'
    implementation group: 'org.glassfish.jersey.core', name: 'jersey-client', version: '2.34'
    implementation group: 'org.glassfish.jersey.connectors', name: 'jersey-apache-connector', version: '2.34'
    implementation group: 'org.glassfish.jersey.inject', name: 'jersey-hk2', version: '2.34'

**Comment by VidhiBhansali** [comment]
@fahmydiab I was able to run an example that uses `ApacheConnectionClosingStrategy` to create `ObjectStorageClient` without explicitly adding a dependency for `ApacheConnectionClosingStrategy`. Can you please compare the configurations with your project? Please refer the `README.md` file to run this example
[gradle-example.zip](https://github.com/oracle/oci-java-sdk/files/7982041/gradle-example.zip)

**Comment by fahmydiab** [comment]
Thank you for reply
