### ISSUE TITLE
Unauthenticated error although my credentials are correct

### ISSUE THREAD

**Issue by fahmydiab** [oracle/oci-java-sdk#356]
com.oracle.bmc.model.BmcException: (401, NotAuthenticated, false) The required information to complete authentication was not provided. (opc-request-id: fra-1:uM7qVWvXFGn1y2Vtbe9wqG-QpFKCN0tcBWFJjdBH8GOoDo4K4lkJl9BjJ0qARFWd)

**Comment by jodoglevy** [comment]
@fahmydiab can you post the code you're using to authenticate? Are you using a config file to get the info, or passing credentials directly in code?

If you use the same credentials / config file with another OCI SDK / tool, does the config file / credentials work?

**Comment by fahmydiab** [comment]
yes the credentials works, the problem was with dependency versions,
    compile group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.7' & '4.5.10'
I changed them and it worked well
