### ISSUE TITLE
Dataflow client is retrying while creating dataflow application which is causing 409 BMC exception

### ISSUE THREAD

**Issue by pateltaruna** [oracle/oci-java-sdk#367]
The retry config for the Dataflow Client is

`public DataFlowClient getDataFlowClient() { final RetryConfiguration DEFAULT_SERVICE_RETRY_CONFIG = RetryConfiguration.builder() .terminationStrategy(new MaxAttemptsTerminationStrategy( (config.getTestConfiguration().getMaxAttempts() == null) ? 5 : config.getTestConfiguration() .getMaxAttempts())) .delayStrategy(new ExponentialBackoffDelayStrategy( ((config.getTestConfiguration().getMaxDelayInMillis() == null) ? TimeUnit.SECONDS.toMillis(30) : config.getTestConfiguration().getMaxDelayInMillis()))) .retryCondition(new DefaultRetryCondition()) .build(); Retriers.setDefaultRetryConfiguration(DEFAULT_SERVICE_RETRY_CONFIG); DataFlowClient client = new DataFlowClient(getAuthProvider(config), null); client.setEndpoint(config.getTestConfiguration().getEndpoint()); return client; }`

**Comment by y-chandra** [comment]
@pateltaruna - What version of the Java SDK is being used in this case? Also, are you manually specifying the value of `opc-retry-token` in the request?

**Comment by jodoglevy** [comment]
@pateltaruna can you please respond to the above? Are you still hitting this issue?

**Comment by pateltaruna** [comment]
jdk version is 8 and from client side we do not specify opc-retry-token  manually.

**Comment by pateltaruna** [comment]
We observed this issue once till now but we need to know the cause.

**Comment by y-chandra** [comment]
@pateltaruna - What version of the Java SDK? It seems you answered the question with the Java version

**Comment by pateltaruna** [comment]
yeah sorry I misread it , the version of SDK is 1.23.5

**Comment by jodoglevy** [comment]
@pateltaruna the version that you're using (v1.23.5) is lower than the version where we fixed an issue around the reuse of retry tokens across retries (in v1.25.0). The issue you're hitting could be due to that (since fixed) issue around retry tokens. Please upgrade to that OCI Java SDK version (or later) and let us know if this issue continues to persist

**Comment by y-chandra** [comment]
@pateltaruna - Any updates on this? We'll be closing this issue if we don't hear back from you in a week. Please feel free to reopen the issue if the problem persists.
