### ISSUE TITLE
No com.oracle.bmc.objectstorage package in API reference documentation page?

### ISSUE THREAD

**Issue by ekumen** [oracle/oci-java-sdk#37]
I don't see com.oracle.bmc.objectstorage package in API reference documentation page: https://docs.us-phoenix-1.oraclecloud.com/tools/java/latest/ ? Is it deleted or moved to other package?

**Comment by jodoglevy** [comment]
Good catch, not sure why it's not showing up there. We'll take a look.

**Comment by nathan-vu** [comment]
I think this is because the module structure changed a bit around Object Storage and so the docs aren't being generated. I'll look at fixing this up.

**Comment by nathan-vu** [comment]
Hi @ekumen, the Object Storage documentation should be available again at: https://docs.us-phoenix-1.oraclecloud.com/tools/java/latest/

If you could take a look again when convenient, that'd be great.

Apologies for the inconvenience caused here.

**Comment by ekumen** [comment]
Thanks @nathan-vu ! I see the Object Storage documentation now.

**Comment by nathan-vu** [comment]
Thanks for checking; sorry again for the inconvenience.
