### ISSUE TITLE
Cannot call any Identity API because of invalid certification path

### ISSUE THREAD

**Issue by luca-poddigue** [oracle/oci-java-sdk#379]
I'm using the latest version of the OCI Java SDK (2.21.0) and trying to get the list of available regions.
I generated the API key via the console and referenced the config file and the private key as reported in the documentation.

However, I always get this error:
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I tried to hit https://identity.eu-milan-1.oci.oraclecloud.com with other clients, and it looks like the server certificate is self signed.
How is that possible? Is there a CA for Oracle certificates? The documentation doesn't mention anything like this.

**Comment by jodoglevy** [comment]
Hi @luca-poddigue - when I go to that URL (https://identity.eu-milan-1.oci.oraclecloud.com/), it works for me and shows the connection is using a valid root-CA-signed certificate:

<img width="481" alt="image" src="https://user-images.githubusercontent.com/234589/161344888-2d4afe10-76f7-42f2-b4e1-f01a2c48d04c.png">

Are you sure there is no proxy sitting between the computer you're trying this from, and OCI? Maybe there is a proxy in between which is using a self-signed certificate. Or maybe your computer is not trusting some standard CA certs?

Do you hit the same SSL issue in either (or both) of these scenarios?
- Targeting a different OCI service (such as compute or audit) in the same OCI region
- Targeting the same OCI service (identity) in a different OCI region (such as ashburn or phoenix)

**Comment by luca-poddigue** [comment]
You are right man, there must be something in between. I tried from another laptop and it worked regularly.
I guess I'll need to get it solved by my company's IT team. This issue can be closed, because it has nothing to do with OCI.

**Comment by luca-poddigue** [comment]
Hi @ihudedi,
As said above, in my case it is something related to how my company internally handles certificates. It happened running the code from Windows under VPN, but for instance, after deploying the same code into a Linux machine, it worked perfectly.
It's not a problem with Oracle.

**Comment by ihudedi** [comment]
Hi @luca-poddigue 
In my laptop under windows it's not working also without VPN.I have antivirus.
In Linux machine it's works.
Thanks,
Itay
