### ISSUE TITLE
Rename packages from bmc => oci

### ISSUE THREAD

**Issue by owainlewis** [oracle/oci-java-sdk#38]
Packages and modules should be renamed from BMC to OCI. Also any documentation referencing BMC.

E.g.

```java
import com.oracle.oci.core.requests.*;
```

**Comment by jodoglevy** [comment]
It's true our current package names don't map to the OCI product naming, but that's actually by design. We decided to leave these names as is so existing customers wouldn't have to take breaking changes to their code, just because of cosmetic product name changes.
