### ISSUE TITLE
Nit: description in bmc-encryption/pom.xml is wrong

### ISSUE THREAD

**Issue by ljnelson** [oracle/oci-java-sdk#383]
Tiny issue. Ran across it and was momentarily confused by the Maven output until I realized it was a copy and paste error.  Didn't want this to get lost.  I'm assuming "`Common`" should be "`Encryption`".

https://github.com/oracle/oci-java-sdk/blob/8672854d536a8acae2065f1ccd35f24297665ee3/bmc-encryption/pom.xml#L13

**Comment by jodoglevy** [comment]
@ljnelson thanks for reporting

**Comment by y-chandra** [comment]
Thanks for reporting. This has been fixed in version `2.25.0`.
