### ISSUE TITLE
json-smart seems to be in the wrong project; should probably move from bmc-common to bmc-encryption

### ISSUE THREAD

**Issue by ljnelson** [oracle/oci-java-sdk#384]
(I would create a PR, but it seems most of this project is generated from elsewhere.  Additionally the `pom.xml`s are not `SNAPSHOT` versions (as of this writing the `master` branch root `pom.xml` says that it is for `<version>2.22.0</version>`, so strictly speaking it would be wrong to patch the `pom.xml` of such an extant version.  So I'll just describe the issue here instead.  It's pretty simple.)

[Currently, in `bmc-common/pom.xml` there is](https://github.com/oracle/oci-java-sdk/blob/v2.22.0/bmc-common/pom.xml#L91-L95):

```xml
<dependency>
    <groupId>net.minidev</groupId>
    <artifactId>json-smart</artifactId>
    <version>2.4.7</version>
</dependency>
```

It is not actually used anywhere in `bmc-common`.  It _is_ used in `bmc-encryption`.  I suggest as a starting point removing this XML from `bmc-common/pom.xml` and placing it in `bmc-encryption/pom.xml` instead.  A full build with Java 8 works with this change.

**Comment by VidhiBhansali** [comment]
Hi @ljnelson. Thanks for suggesting the changes. I am looking into it.

**Comment by VidhiBhansali** [comment]
@ljnelson We've fixed the `pom.xml` in version **2.39.0** of the OCI Java SDK. Closing this issue since it has been resolved from our end but please feel free to reopen if it is still an issue after upgrading to 2.39.0.
