### ISSUE TITLE
Spurious dependencies in bmc-encryption

### ISSUE THREAD

**Issue by ljnelson** [oracle/oci-java-sdk#385]
(I know I'm filing a lot of "issues".  They're all tiny.  Just noticing things as I dig into the project and don't want them to get lost, that's all.  Do with them what you will!)

I noticed that the following dependencies, when removed entirely from `bmc-encryption`, do not impact a full build (with tests) in any way:

```xml
<dependency>
    <groupId>com.fasterxml.jackson.datatype</groupId>
    <artifactId>jackson-datatype-jsr310</artifactId>
</dependency>
<dependency>
    <groupId>com.fasterxml.jackson.datatype</groupId>
    <artifactId>jackson-datatype-jdk8</artifactId>
</dependency>
```

**Comment by ljnelson** [comment]
I can also remove these as well from `bmc-common` with no ill effects.  Perhaps they are needed at runtime, in which case perhaps they should continue to be declared in both projects but in `<scope>runtime</scope>`?  Or perhaps they truly are not needed at all in either project.

**Comment by VidhiBhansali** [comment]
Hi @ljnelson. Thanks for suggesting the changes. I am looking into it.

**Comment by VidhiBhansali** [comment]
@ljnelson We've fixed the `pom.xml` in version **2.39.0** of the OCI Java SDK. Closing this issue since it has been resolved from our end but please feel free to reopen if it is still an issue after upgrading to 2.39.0.
