### ISSUE TITLE
resteasy-client-configurator seemingly only needs a dependency on resteasy-core

### ISSUE THREAD

**Issue by ljnelson** [oracle/oci-java-sdk#386]
In `bmc-resteasy-client-configurator/pom.xml` there is a dependency on `resteasy-client`, for no good reason.  The dependency needs to be on `resteasy-core`.

There are also some sketches in this file that seem to indicate that what is really desired is an entry in `../../pom.xml`'s `<dependencyManagement>` section, so that the Apache `httpcomponents` stuff is version managed all the way down the dependency tree.  What is currently present in this `pom.xml` file does not accomplish what it seems to want to accomplish.

**Comment by VidhiBhansali** [comment]
Hi @ljnelson. Thanks for suggesting the changes. I am looking into it.

**Comment by VidhiBhansali** [comment]
@ljnelson We've fixed the `pom.xml` in version **2.39.0** of the OCI Java SDK. Closing this issue since it has been resolved from our end but please feel free to reopen if it is still an issue after upgrading to 2.39.0.
