### ISSUE TITLE
bmc-shaded-full is strange

### ISSUE THREAD

**Issue by ljnelson** [oracle/oci-java-sdk#387]
See:

https://github.com/oracle/oci-java-sdk/blob/v2.22.0/bmc-shaded/bmc-shaded-full/pom.xml#L14-L30

Do I understand correctly that this module is _intended_ to produce a `.jar` file consisting of some kind of shaded version of the entire OCI SDK?  As presently constituted, this `pom.xml` will, unless I'm missing something, produce an empty `.jar` file.  Its transitive dependencies will consist solely of a few BouncyCastle jars and the SLF4J API jar.  Right?  I feel like maybe something got dropped here.

**Comment by VidhiBhansali** [comment]
Hi @ljnelson. Thanks for suggesting the changes. I am looking into it.

**Comment by VidhiBhansali** [comment]
@ljnelson This might be looking weird but there is not much we can do right now. Closing this issue since we do not expect any work around this. Please feel free to reopen if you still think it is an issue.
