### ISSUE TITLE
Object Storage: Need support for updating object metadata

### ISSUE THREAD

**Issue by nithin-ks** [oracle/oci-java-sdk#394]
Currently, In oci  object storage, once an object gets created.
Is there a way to update the object metadata at a later point?

If not, would it be possible to provide this feature, as it would be really helpful for us. 

Thanks in advance.

**Comment by KartikShrikantHegde** [comment]
Hi Nithin,

Currently, we don't have an API that supports updating metadata. (If you are just looking to rename the object you can use ranameObject APi).

I will ask Object Storage team to triage the request.

Thanks
Kartik

**Comment by meghaagarwal-dev** [comment]
As Karthik Mentioned we don't support updating metadata. However we might take this in future. 
Thanks
Megha

**Comment by KartikShrikantHegde** [comment]
@nithin-ks I am closing this ticket for now. Please feel free to re-open if you need additional help.

**Comment by KartikShrikantHegde** [comment]
Ticket re-opened for the community to see and up-vote on this.

**Comment by lra** [comment]
Is there any news on this issue?
