### ISSUE TITLE
Thread-safety of ServiceDetails

### ISSUE THREAD

**Issue by martijndwars** [oracle/oci-java-sdk#403]
Hi,

Issue #122 mentions that "the SDK clients are thread-safe after they are initialized." The official [OCI Java SDK documentation](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/javasdkconcepts.htm#Threading_Model) mentions that "you can safely use a client in multiple threads and concurrently call methods on it." This sounds great!

However, when making multiple asynchronous calls, the error messages are NOT thread safe, because:

1. All clients (including the asynchronous clients `<Service>AsyncClient`) call a _static_ method `ServiceDetails.setServiceDetails` with the service, operation, request URI, and OCI docs URL.
2. The `ServiceDetails.setServiceDetails` method updates the _static_ fields in the `ServiceDetails` class. That means that multiple asynchronous calls are writing to the _same_ fields.
3. When a request fails (e.g. 403, 404, or 500 status code), the client converts the response to a `BmcException`. The `BmcException.toString()` method reads the _static_ fields in the `ServiceDetails` class.
4. Depending on when you call `BmcException.toString()`, you may get an error message that contains an operation name, request endpoint, and API reference link for a _different_ request. To make matters worse, this other request may not even have failed.

Is this analysis correct? What am I missing here?

Thanks,

Martijn

**Comment by martijndwars** [comment]
For what it's worth, it looks like this bug was introduced in version [2.23.0](https://github.com/oracle/oci-java-sdk/blob/28f901583343901df3056c55c2c1763cc2ac00d5/bmc-common/src/main/java/com/oracle/bmc/model/BmcException.java) of the OCI Java SDK. Older versions are not affected.

**Comment by y-chandra** [comment]
@martijndwars - Thank you for reporting this issue. We're actively working on the fix and will keep you posted with any updates.

**Comment by martijndwars** [comment]
Thanks @y-chandra. Any update so far?

**Comment by y-chandra** [comment]
@martijndwars - We've fixed this issue in version `2.35.0` of the Java SDK. Please upgrade to this version. We're closing this issue since it has been resolved from our end, please feel free to reopen if you still face the issue after upgrading to the above mentioned version.
