### ISSUE TITLE
Request to upgrade error_prone_annotations package to at least version 2.11.0

### ISSUE THREAD

**Issue by davalos-adrian** [oracle/oci-java-sdk#408]
This would be very helpful since our security team is giving this requirement.

I could just upgrade it myself but I'd have to do it every time we upgrade oci java sdk and this could lead to human error.

Thank you very much!

**Comment by jodoglevy** [comment]
Hi @davalos-adrian - is there a security vulnerability with the version of error_prone_annotations used by the SDK today? We haven't seen one. We'd like to know more about why your security team is not ok with the current version of that dependency.

**Comment by mricken** [comment]
This dependency comes in via Guava.

```
[INFO] +- com.google.guava:guava:jar:31.0.1-jre:compile
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- org.checkerframework:checker-qual:jar:3.12.0:compile
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.7.1:compile
```

We're actually working on removing Guava as a dependency of the OCI Java SDK. This is, however, still a few months in the future.

**Comment by mricken** [comment]
Considering this package contains annotations to control static analysis to find common errors, which happens at build time and not at runtime, I don't see an urgent need to upgrade our Guava version.

Like I said, we are working on removing Guava entirely. Please feel free to re-open if you disagree.
