### ISSUE TITLE
Release full shaded jar to Maven Central

### ISSUE THREAD

**Issue by ljnelson** [oracle/oci-java-sdk#410]
See #371 for background and an offer by @mricken to release the full shaded jar.  This issue is just to track the release of the 96MB shaded jar to Maven Central as was originally offered.

**Comment by mricken** [comment]
Hi @ljnelson , I have recommended that we prioritize this work. Thank you.

**Comment by ljnelson** [comment]
Glad to hear it; thanks!

**Comment by jodoglevy** [comment]
Hi @ljnelson - I'm currently talking to Dmitry from the Oracle Helidon team to work out the priority of this vs other deliverables. Thanks for you patience.

**Comment by mricken** [comment]
@ljnelson , you are right, thank you for pointing that out. We'll work on fixing this next. Inclyding the oci-java-sdk-shaded pom.xml file should not be very difficult.

**Comment by mricken** [comment]
Fix should go out on Tuesday, July 26, 2022.

**Comment by ljnelson** [comment]
I was able to download the full shaded jar using Maven. Thank you.

**Comment by VidhiBhansali** [comment]
Thanks @ljnelson. Closing the issue since you were able to download the full shaded jar using Maven.
