### ISSUE TITLE
Unable to replay the stream by using the time

### ISSUE THREAD

**Issue by kollachaitanyakrishna** [oracle/oci-java-sdk#413]
As per the example provided, "https://github.com/oracle/oci-java-sdk/blob/master/bmc-examples/src/main/java/StreamsExample.java". The messages can be consumed using the partition / group. 

They are looking for a solution to replay of the messages using the timestamp.

**Comment by KartikShrikantHegde** [comment]
Hi @kollachaitanyakrishna ,

Thanks for your request. We will ask our concerned team to take a look at this and provide an update.

Thanks,
Kartik
