### ISSUE TITLE
Javadoc suddenly omits services?

### ISSUE THREAD

**Issue by ljnelson** [oracle/oci-java-sdk#419]
I did a search for `ObjectStorageClient` in my browser while browsing https://docs.oracle.com/en-us/iaas/tools/java/2.35.0/index.html and https://docs.oracle.com/en-us/iaas/tools/java/2.36.0/index.html and the only hit was in some example text.

This worked as of version 2.19.0 and possibly later.  I'm not sure when the `objectstorage` service documentation was eliminated from the overall javadocs.

(The actual service `.jar` file is present in Maven Central, i.e. the code is usable: https://search.maven.org/artifact/com.oracle.oci.sdk/oci-java-sdk-objectstorage/2.36.0/jar.)

**Comment by ljnelson** [comment]
I've also noticed that for, e.g., https://docs.oracle.com/en-us/iaas/tools/java/2.36.0/index.html, the `2.36.0` part will "accept" a string equal to the latest version available (`2.36.0` as of this writing), or one version "less than" it, and no other (i.e. `2.35.0` as of this writing is also valid, but `2.34.0` is not).

Any other "version string" will get redirected to the latest version available, i.e. https://docs.oracle.com/en-us/iaas/tools/java/2.35.0/index.html and https://docs.oracle.com/en-us/iaas/tools/java/2.36.0/index.html.

If maintaining persistent versioned javadoc websites is difficult or impossible, consider the standard Maven practice of uploading various javadoc `.jar` files so that [javadoc.io](https://javadoc.io/) will pick them up and archive them automatically.  See https://central.sonatype.org/publish/requirements/#deployment; if such javadoc jars are uploaded according to the principles described by this document then javadoc.io will produce a website for you for each released version and archive it effectively indefinitely.  As a completely arbitrary example, here is [Helidon's OCI Object Storage integration javadoc website](https://javadoc.io/doc/io.helidon.integrations.cdi/helidon-integrations-cdi-oci-objectstorage/latest/io.helidon.integrations.cdi.oci.objectstorage/module-summary.html) (pull down on the version menu to see just how deep the rabbit hole goes).  The Helidon project doesn't build or host these websites; they're automatically built from the javadocs the Helidon project uploads to Maven Central [according to Sonatype's Maven Central requirements](https://central.sonatype.org/publish/requirements/#deployment).  It's a convenient way to archive old versions.

**Comment by KartikShrikantHegde** [comment]
Hi @ljnelson ,

Thanks for reporting the issue. Our team will take a look and get back to you.

Thanks.

**Comment by ZiyaoQiao** [comment]
Hi @ljnelson this issue is resolved in 2.38.0 and the objectStorage doc is now back. Due to some limitations, we're only able to publish 2 latest versions. You can find all docs for past versions in Github releases. Thanks

**Comment by ljnelson** [comment]
That is good to know. Please consider uploading javadoc jars for individual modules (they're actually required, technically, by Maven Central) following [good Maven Central practice](https://central.sonatype.org/publish/requirements/); then javadocs for all versions are handled for you via [javadoc.io](https://javadoc.io/).

**Comment by mricken** [comment]
The Javadoc is uploaded per module to Maven Central. Otherwise, the Maven Central deployment would fail.

See, for example:

https://repo1.maven.org/maven2/com/oracle/oci/sdk/oci-java-sdk-objectstorage-generated/2.38.0/
https://repo1.maven.org/maven2/com/oracle/oci/sdk/oci-java-sdk-objectstorage-generated/2.37.0/
https://repo1.maven.org/maven2/com/oracle/oci/sdk/oci-java-sdk-objectstorage-generated/2.19.0/

**Comment by ljnelson** [comment]
Oh, that's good news!
