### ISSUE TITLE
oci-java-sdk-shaded-full is not present in oci-java-sdk-bom

### ISSUE THREAD

**Issue by ljnelson** [oracle/oci-java-sdk#425]
It probably should be.  Same, I presume, with `oci-java-sdk-shaded`.

**Comment by mricken** [comment]
Hi @ljnelson , adding them is probably fine. But can you explain why you would use both the shaded module and the bom?

**Comment by ljnelson** [comment]
Mostly I just noticed that this is an artifact that this project produces, but it is not present in its bill-of-materials.

I could think of several use cases where perhaps the `javax`/`jakarta` package name clashes would not be so significant as to warrant usage of a big artifact when the individual ones might work; you might want to share a BOM in such cases.

**Comment by VidhiBhansali** [comment]
Closing this issue since `oci-java-sdk-full-shaded` has been added to `oci-java-sdk-bom` - [pom.xml](https://github.com/oracle/oci-java-sdk/blob/master/bmc-bom/pom.xml#L40). Please feel free to reopen if you still think it is an issue.
