### ISSUE TITLE
Can't specify hostname in CreateListenerDetails

### ISSUE THREAD

**Issue by stanicek** [oracle/oci-java-sdk#45]
Example in the help shows how to specify hostname for load balancer's listener. But this option is not available in SDK. 

https://docs.us-phoenix-1.oraclecloud.com/api/#/en/loadbalancer/20170115/requests/CreateListenerDetails

Is the example misleading or is it missing in the SDK (1.2.28)?

`{
  "defaultBackendSetName": "example_backend_set",
  "port": 80,
  "protocol": "HTTP",
  "hostname": "app.example.com",
  "pathRouteSetName": "example_path_route_set",
  "sslConfiguration": {
    "certificateName": "example_certificate_bundle",
    "verifyPeerCertificate": true,
    "verifyDepth": 3
  },
  "connectionConfiguration": {
    "idleTimeout": 1200
  },
  "name": "example_listener"
}` 

Thanks

**Comment by priteshkp** [comment]
Hey Josef, we're following up with the Load Balancer team and will let you know what we find out.

**Comment by benthamc** [comment]
Hi Josef, SDK is correct and we will remove hostname usage from the example. Thanks for reaching out to us!

**Comment by stanicek** [comment]
Thanks

I did a bit of debugging of API calls from LB UI and I can see what I need under a property "serverName". Do you plan to add it soon or is it some kind of beta feature which LB team may change thus it is not implemented in SDK? Hostname is the name of the field in UI.

`"test1": {
        "connectionConfiguration": {
          "idleTimeout": 60
        },
        "defaultBackendSetName": "ns-backend-set",
        "name": "test1",
        "port": 443,
        "protocol": "HTTP",
        "serverName": "www.fake-domain-lb-test1.com",
        "sslConfiguration": {
          "certificateName": "www.fake-domain-lb-test1.com",
          "verifyDepth": 1,
          "verifyPeerCertificate": false
        }
      }`

**Comment by nathan-vu** [comment]
> Do you plan to add it soon or is it some kind of beta feature which LB team may change thus it is not implemented in SDK? 

It's more the latter. I wouldn't say the feature is truly beta, since it's doable through the console, but from an API perspective how this is done may change and so it's not exposed via the SDKs or CLI yet.
