### ISSUE TITLE
Warnings showing up in the log output for programming tips

### ISSUE THREAD

**Issue by robertpatrick** [oracle/oci-java-sdk#453]
I am using the [oci-maven-plugin](https://github.com/kordamp/oci-maven-plugin) to interact with object storage.  When downloading an object, we are seeing the following warnings for which the user of the plugin goal does not need to know and cannot do anything about.  These messages, which appear to be programming tips, seem to be more appropriate as `info` (or `debug`) level messages and not warnings.

```
[WARNING] getObject returns a stream, please make sure to close the stream to avoid any indefinite hangs
[WARNING] ApacheConnectionClosingStrategy set to org.glassfish.jersey.apache.connector.ApacheConnectionClosingStrategy$ImmediateClosingStrategy@1e734eee. For large streams with partial reads of stream, please use ImmediateClosingStrategy. For small streams with partial reads of stream, please use GracefulClosingStrategy. More info in ApacheConnectorProperties
[WARNING] Wrapping response stream into auto closeable stream, to disable this, please use com.oracle.bmc.Options.shouldAutoCloseResponseInputStream(false)
```

See [oci-maven-plugin Issue #7](https://github.com/kordamp/oci-maven-plugin/issues/7) for more information.

**Comment by y-chandra** [comment]
To disable the above warnings by following the steps described [here](https://github.com/oracle/oci-java-sdk/blob/master/ApacheConnector-README.md#disabling-extra-logs-related-to-streams)

**Comment by y-chandra** [comment]
Does the above workaround resolve the issue? We'll close this issue soon since we haven't heard back from you in a while. Please feel free to reopen if the problem persists
