### ISSUE TITLE
Unable to fetch the Event Location via Audit Event

### ISSUE THREAD

**Issue by aunayak** [oracle/oci-java-sdk#49]
Hi,
I have been using AuditEvent to fetch the IP of the event to locate from where the event was generated, I have been using getRequestOrigin() to get the IP. but i am getting the private IP instead of real IP. so i am unable to locate the event location.
Can you please suggest the way how can i get the real IP for monitoring the event location.

Sample Audit Event Log below.

{"log":"AuditEvent(tenantId=ocid1.tenancy.oc1..aaaaaaaaepmjkbko4fybhvt6wrakf7gw6ssjflkdkxnsxohysd3ymlzxdzoq, compartmentId=ocid1.tenancy.oc1..aaaaaaaaepmjkbko4fybhvt6wrakf7gw6ssjflkdkxnsxohysd3ymlzxdzoq, eventId=bc41c9fe-eb6d-4494-ad54-975c703d23bf, eventSource=IdentityProvisioning, eventType=ServiceApi, eventTime=Tue Mar 27 15:33:35 IST 2018, principalId=ocid1.user.oc1..aaaaaaaag5fwyrkaazc2ktjmqe7xkmgjxy2wnw2hdytweyym7fzo73m47q3a, credentialId=ST$eyJraWQiOiJhc3ciLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJvY2lkMS51c2VyLm9jMS4uYWFhYWFhYWFnNWZ3eXJrYWF6YzJrdGptcWU3eGttZ2p4eTJ3bncyaGR5dHdleXltN2Z6bzczbTQ3cTNhIiwiYXVkIjoib2NpIiwicHN0eXBlIjoibmF0diIsInR0eXBlIjoibG9naW4iLCJpc3MiOiJhdXRoU2VydmljZS5vcmFjbGUuY29tIiwicHR5cGUiOiJ1c2VyIiwic2Vzc19leHAiOiJXZWQsIDI4IE1hciAyMDE4IDA5OjUwOjQ2IFVUQyIsImV4cCI6MTUyMjE0Nzg0NiwiaWF0IjoxNTIyMTQ0MjQ2LCJqdGkiOiI4OGU4NmQ4MC05MjJjLTQ4MjQtYTk1Yi05NjUwZGYxMmQ2OWQiLCJ0ZW5hbnQiOiJvY2lkMS50ZW5hbmN5Lm9jMS4uYWFhYWFhYWFlcG1qa2JrbzRmeWJodnQ2d3Jha2Y3Z3c2c3NqZmxrZGt4bnN4b2h5c2QzeW1senhkem9xIiwiandrIjoie1wiYWxnXCI6XCJSUzI1NlwiLFwiZVwiOlwiQVFBQlwiLFwiZXh0XCI6dHJ1ZSxcImtleV9vcHNcIjpbXCJ2ZXJpZnlcIl0sXCJrdHlcIjpcIlJTQVwiLFwiblwiOlwidk1PRVNYNlVDY0RtVkJVV2xEQncwMWxnY25yaXpDWDdXT0VTNFBVM0ktX29uZDBPcDBGYk9UZlF5Y1FzdFFubDhNS25idGVRWGhuazAxWFFiZFcwa3pCaVhWNk9hMjI1WFUtZ0tuSjZncGg4UGZCWWxnN2RjVm1TaWQ1Z3h4VTFRSWpXN3lJeHNWa1BMUmhFaWdsSnlEVXNLSGVCRGhOWWdSbGVGalFIWjBkQXJVSmNuTC04cW1fYXdFQ2N3VWxtWnloaDF1R0dCSUJvWjRQNXhtUDJsdnFBaWJKU003ZTNfdzhSMHFDNTgxN2NIZjNNX0dHWUVGMGZXeG5tMV9HdzlUbjZUSFlYZERLb042b2pBb3MyWVVYYUxaeU5PREZpeE5UUUNSczc5cmlkTk9uRk5HbzRHZl9EWmlFTF81Y1NHUWNqMVdQX3psRFJQdUZVeHNvNDdRXCIsXCJraWRcIjpcInB1YmtleS1kNzA1OTcyMi02NmE4LTQzNTEtOGJkZi0zNTllZGExMTA2NDZcIn0ifQ.gLKoL_GTpJAh5JUAIX4lRny2kTQrDbWlETfZCPfPd76EUJsBFm_cBJ-LSD1oEHzBjzbDOB03Ur2nawjKZ72H1uqVPlksA3G3zixbAAZKYsdc6nqqJczQGZJSWWPipmuwrCL1JkZexjmlezzl-HnOoohOK2uYjmuHQpb3Oc5_b-AIJqQsECmuJj8lMO4cLD9hRSYw_NQql7b2kgXiD_BvGESSeAbPiyJpklADvAk12ABTg1YNdYbz_BB17GW4I5zfYTq9Goi4dlHdwkg1HrapgJbdgtxR1s9aSL8fYqYkN94jJxGx6ZQATc5txqSaoRZdKWHpfjDHi8VBmkLonPIAoA, requestAction=POST, requestId=0f4a8fdf-e959-4c05-825b-2016113c/3DE1CC59F187BBC76AF2EF804EFC4E3A/5046B7C959C3A745C9ADCDC12B2CCBCC, requestAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36, requestHeaders={Origin=[https://console.us-phoenix-1.oraclecloud.com], X-Content-Sha256=[+6zogZfaGXzopwA5oK09aB0hklN/7dUNn1Jeb9hfdAA=], Accept=[*/*], X-Date=[Tue, 27 Mar 2018 10:03:35 GMT], X-Forwarded-Proto=[https], X-Forwarded-Host=[identity.us-phoenix-1.oraclecloud.com:443], User-Agent=[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36], Referer=[https://console.us-phoenix-1.oraclecloud.com/a/identity/users], Accept-Encoding=[gzip, deflate, br], X-Forwarded-Port=[443], Authorization=[Signature keyId=\"ST$eyJraWQiOiJhc3ciLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJvY2lkMS51c2VyLm9jMS4uYWFhYWFhYWFnNWZ3eXJrYWF6YzJrdGptcWU3eGttZ2p4eTJ3bncyaGR5dHdleXltN2Z6bzczbTQ3cTNhIiwiYXVkIjoib2NpIiwicHN0eXBlIjoibmF0diIsInR0eXBlIjoibG9naW4iLCJpc3MiOiJhdXRoU2VydmljZS5vcmFjbGUuY29tIiwicHR5cGUiOiJ1c2VyIiwic2Vzc19leHAiOiJXZWQsIDI4IE1hciAyMDE4IDA5OjUwOjQ2IFVUQyIsImV4cCI6MTUyMjE0Nzg0NiwiaWF0IjoxNTIyMTQ0MjQ2LCJqdGkiOiI4OGU4NmQ4MC05MjJjLTQ4MjQtYTk1Yi05NjUwZGYxMmQ2OWQiLCJ0ZW5hbnQiOiJvY2lkMS50ZW5hbmN5Lm9jMS4uYWFhYWFhYWFlcG1qa2JrbzRmeWJodnQ2d3Jha2Y3Z3c2c3NqZmxrZGt4bnN4b2h5c2QzeW1senhkem9xIiwiandrIjoie1wiYWxnXCI6XCJSUzI1NlwiLFwiZVwiOlwiQVFBQlwiLFwiZXh0XCI6dHJ1ZSxcImtleV9vcHNcIjpbXCJ2ZXJpZnlcIl0sXCJrdHlcIjpcIlJTQVwiLFwiblwiOlwidk1PRVNYNlVDY0RtVkJVV2xEQncwMWxnY25yaXpDWDdXT0VTNFBVM0ktX29uZDBPcDBGYk9UZlF5Y1FzdFFubDhNS25idGVRWGhuazAxWFFiZFcwa3pCaVhWNk9hMjI1WFUtZ0tuSjZncGg4UGZCWWxnN2RjVm1TaWQ1Z3h4VTFRSWpXN3lJeHNWa1BMUmhFaWdsSnlEVXNLSGVCRGhOWWdSbGVGalFIWjBkQXJVSmNuTC04cW1fYXdFQ2N3VWxtWnloaDF1R0dCSUJvWjRQNXhtUDJsdnFBaWJKU003ZTNfdzhSMHFDNTgxN2NIZjNNX0dHWUVGMGZXeG5tMV9HdzlUbjZUSFlYZERLb042b2pBb3MyWVVYYUxaeU5PREZpeE5UUUNSczc5cmlkTk9uRk5HbzRHZl9EWmlFTF81Y1NHUWNqMVdQX3psRFJQdUZVeHNvNDdRXCIsXCJraWRcIjpcInB1YmtleS1kNzA1OTcyMi02NmE4LTQzNTEtOGJkZi0zNTllZGExMTA2NDZcIn0ifQ.gLKoL_GTpJAh5JUAIX4lRny2kTQrDbWlETfZCPfPd76EUJsBFm_cBJ-LSD1oEHzBjzbDOB03Ur2nawjKZ72H1uqVPlksA3G3zixbAAZKYsdc6nqqJczQGZJSWWPipmuwrCL1JkZexjmlezzl-HnOoohOK2uYjmuHQpb3Oc5_b-AIJqQsECmuJj8lMO4cLD9hRSYw_NQql7b2kgXiD_BvGESSeAbPiyJpklADvAk12ABTg1YNdYbz_BB17GW4I5zfYTq9Goi4dlHdwkg1HrapgJbdgtxR1s9aSL8fYqYkN94jJxGx6ZQATc5txqSaoRZdKWHpfjDHi8VBmkLonPIAoA\",version=\"1\",algorithm=\"rsa-sha256\",headers=\"(request-target) host content-length opc-client-info x-date opc-request-id content-type x-content-sha256\",signature=\"*****\"], Opc-Request-Id=[0f4a8fdf-e959-4c05-825b-2016113c9e30], X-Forwarded-For=[160.34.126.47], Opc-Client-Info=[Oracle-HgConsole/0.0.1], Accept-Language=[en-GB,en-US;q=0.9,en;q=0.8], Content-Length=[203], X-Real-IP=[160.34.126.47], Content-Type=[application/json]}, requestOrigin=172.24.112.149, requestParameters={}, requestResource=/20160918/users/, responseHeaders={Access-Control-Expose-Headers=[opc-previous-page,opc-next-page,opc-client-info,ETag,opc-request-id,Location], Access-Control-Allow-Origin=[https://console.us-phoenix-1.oraclecloud.com], ETag=[eb7bc6f3628daef80172fd5d65a3583467b25db6], Access-Control-Allow-Credentials=[true], Content-Length=[397], opc-request-id=[0f4a8fdf-e959-4c05-825b-2016113c/3DE1CC59F187BBC76AF2EF804EFC4E3A/5046B7C959C3A745C9ADCDC12B2CCBCC], Date=[Tue, 27 Mar 2018 10:03:35 GMT], Location=[http://identity.us-phoenix-1.oraclecloud.com/20160918/users/ocid1.user.oc1..aaaaaaaag32nkv2wqpp25hzpkbpaylvcds52jztuy5c2ck6q7gbum6ooj6jq], Content-Type=[application/json]}, responseStatus=200, responseTime=Tue Mar 27 15:33:35 IST 2018, responsePayload={id=ocid1.user.oc1..aaaaaaaag32nkv2wqpp25hzpkbpaylvcds52jztuy5c2ck6q7gbum6ooj6jq}, __explicitlySet__=[requestResource, eventId, requestAction, requestOrigin, responseTime, responsePayload, eventSource, requestParameters, principalId, eventType, responseStatus, compartmentId, requestHeaders, responseHeaders, requestId, requestAgent, tenantId, eventTime, credentialId])"}

**Comment by benthamc** [comment]
According to the Content of Event Log data document: 
https://docs.us-phoenix-1.oraclecloud.com/Content/Audit/Reference/logeventreference.htm
getRequestOrigin() is the one we exposed at this point. We will communicate with Audit service team to consider exposing X-Real-IP.

Thanks!
Bentham

**Comment by aunayak** [comment]
Can you please update the status on this issue.

**Comment by jodoglevy** [comment]
This doesn't seem to be an issue with the SDK itself, but rather the Audit service. We've reached out to the Audit service team to respond to you here.

**Comment by pritams21** [comment]
Currently we are exposing the requestOrigin, but seems for the services behind proxy/LB, this ends up logging the proxy/LB IP, thus internal IP. We are working on fixing that part.

**Comment by nejajain** [comment]
There is X-Real-IP under requestHeader which can be used to get the IP. We have requestOrigin field which is also logging the IP. 
We have yet not started working on the cases where requestOrigin is logging internal IP.
