### ISSUE TITLE
Database Example

### ISSUE THREAD

**Issue by buffaloforge** [oracle/oci-java-sdk#51]
Are there any examples of creating a database instance using the java api?  I see a compute node, but not database

**Comment by benthamc** [comment]
No, we don't have one. There is a Python example:
https://github.com/oracle/oci-python-sdk/blob/master/examples/launch_db_system_example.py
I will port it to Java in next release.

Thanks,
Bentham

**Comment by benthamc** [comment]
We have added an example in this release [here](
https://github.com/oracle/oci-java-sdk/blob/master/bmc-examples/src/main/java/LaunchDbSystemExample.java). Thanks for reaching out to us!
