### ISSUE TITLE
BmcException provides no public getters for http status code / opc request id etc.

### ISSUE THREAD

**Issue by matthewshannon** [oracle/oci-java-sdk#52]
Currently only reflection hacks could be leveraged to get at underlying BcmException properties such as status code short of trying to rip the data out from getMessage().

Some getters would be most useful.

https://github.com/oracle/oci-java-sdk/blob/master/bmc-common/src/main/java/com/oracle/bmc/model/BmcException.java

**Comment by priteshkp** [comment]
@matthewshannon the getters are auto-generated by Lombok (the @Getter annotation on each field).  You do not need to use reflection

https://docs.us-phoenix-1.oraclecloud.com/Content/API/SDKDocs/javasdk.htm#exceptions

```
ObjectStorage client = ...;
try {
    GetBucketResponse response = client.getBucket(
	        GetBucketRequest.builder().namespaceName("myNamespace").bucketName("myBucket").build());
    String requestId = response.getOpcRequestId();
    System.out.println(requestId);
} catch (BmcException e) {
    String requestId = e.getOpcRequestId();
    System.out.println(requestId);
    e.printStackTrace();
}
```
