### ISSUE TITLE
Releases does not include pom.xml file

### ISSUE THREAD

**Issue by galvinograd** [oracle/oci-java-sdk#53]
Hey,

I'm trying to publish the Github release into my internal maven repository. The client's dependencies does not resolve since the Jar does not contain pom.xml. As a workaround I'm using the shaded version.

Can you please include pom.xml in your next release?

Thanks :)

**Comment by benthamc** [comment]
Yes, we will consider that. Thanks for reaching out to us.

**Comment by mricken** [comment]
Hi Gal,

Can you describe which jar you need to contain a pom.xml file?

Thanks,

--Mathias

**Comment by mricken** [comment]
I guess you're talking about a pom.xml file that allows you to use ./lib/oci-java-sdk-full-1.2.33.jar, correct?

**Comment by galvinograd** [comment]
yes

**Comment by mricken** [comment]
I finished implementing this. It will be part of our next release.

Thanks for the suggestion!
