### ISSUE TITLE
Got HTTP 407 CACHE_ACCESS_DENIED from Squid proxy server when authentication is enabled

### ISSUE THREAD

**Issue by lryckman** [oracle/oci-java-sdk#549]
I have client code like in this sample - https://github.com/oracle/oci-java-sdk/blob/master/bmc-examples/src/main/java/HttpProxyExample.java. I am getting Cache Access Denied exception listing regions using IdentityClient. The proxy server is a Squid server. The invocation works correctly if the proxy server authentication is off. Any suggestions? Thank you.

 "message": "Failed to list IAM region com.oracle.bmc.model.BmcException: Error returned by ListRegions operation in Identity service.(407, Unknown, false) Unexpected Content-Type: text/html;charset=utf-8 instead of application/json. Response body: <!DOCTYPE html PUBLIC '-//W3C//DTD HTML 4.01//EN' 'http://www.w3.org/TR/html4/strict.dtd'> <html><head> <meta type='copyright' content='Copyright (C) 1996-2021 The Squid Software Foundation and contributors'> <meta http-equiv='Content-Type' content='text/html; charset=utf-8'> <title>ERROR: Cache Access Denied</title> <style type='text/css'></style> </head><body id=ERR_CACHE_ACCESS_DENIED> <div id='titles'> <h1>ERROR</h1> <h2>Cache Access Denied.</h2> </div> <hr>  <div id='content'> <p>The following error was encountered while trying to retrieve the URL: <a href='https://identity.us-phoenix-1.oci.oraclecloud.com/*'>https://identity.us-phoenix-1.oci.oraclecloud.com/*</a></p>  <blockquote id='error'> <p><b>Cache Access Denied.</b></p> </blockquote>  <p>Sorry, you are not currently allowed to request https://identity.us-phoenix-1.oci.oraclecloud.com/* from this cache until you have authenticated yourself.</p>  <p>Please contact the <a href='mailto:root?subject=CacheErrorInfo%20-%20ERR_CACHE_ACCESS_DENIED&amp;body=CacheHost%3A%20c3-proxy-2%0D%0AErrPage%3A%20ERR_CACHE_ACCESS_DENIED%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Mon,%2018%20Sep%202023%2016%3A08%3A10%20GMT%0D%0A%0D%0AClientIP%3A%2010.80.170.188%0D%0A%0D%0AHTTP%20Request%3A%0D%0ACONNECT%20%20HTTP%2F1.1%0AUser-Agent%3A%20Apache-HttpClient%2F4.5.14%20(Java%2F1.8.0_301)%0D%0AHost%3A%20identity.us-phoenix-1.oci.oraclecloud.com%3A443%0D%0A%0D%0A%0D%0A'>cache administrator</a> if you have difficulties authenticating yourself.</p>  <br> </div>  <hr>  <div id='footer'> <p>Generated Mon, 18 Sep 2023 16:08:10 GMT by c3-proxy-2 (squid/4.15)</p>  </div> </body></html>  Timestamp: 2023-09-18T16:08:10.747Z Client version: Oracle-JavaSDK/3.17.1 Request Endpoint: https://identity.us-phoenix-1.oci.oraclecloud.com/20160918/regions Troubleshooting Tips: See https://docs.oracle.com/en-us/iaas/Content/API/References/apierrors.htm#apierrors_407__407_unknown for more information about resolving this error Also see https://docs.oracle.com/iaas/api/#/en/identity/20160918/Region/ListRegions for details on this operation's requirements. To get more info on the failing request, you can enable debug level logs as mentioned in `Using SLF4J for Logging section` in https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/javasdkconfig.htm. If you are unable to resolve this Identity issue, please contact Oracle support and provide them this full error message."

**Comment by KartikShrikantHegde** [comment]
Hi @lryckman , have you tried testing this without SDK, like `curl`? If it doesn't work with 'curl' then it might be an issue with proxy server configuration rather than a client issue.

Also, can you enable debug logs and share the detailed log?

**Comment by lryckman** [comment]
Thank you for your response. The java sdk team has confirmed that there is a bug in the Jersey3 http client where the proxy password is not extracted correctly. I believe a fix will be available soon. You can consider this item closed.

**Comment by jyotisaini** [comment]
This has been fixed as part of the latest release. Closing this ticket.
