### ISSUE TITLE
Exception in getNamespace api

### ISSUE THREAD

**Issue by aunayak** [oracle/oci-java-sdk#56]
Hi I am trying to use the getNamespace api and i am getting the error using it, Can you please look into this and guide if i am using the api in right way?

 final String namespace =
                objectStorageClient.getNamespace(GetNamespaceRequest.builder().build()).getValue();

Exception details:
javax.ws.rs.ProcessingException: RESTEASY003145: Unable to find a MessageBodyReader of content-type application/json and type class java.lang.String

**Comment by benthamc** [comment]
Your code looks good. I will need more info from you we can take this offline .

**Comment by benthamc** [comment]
Hi Avinash, this issue has been resolved in release 1.2.37. Thanks for reaching out to us.
