### ISSUE TITLE
Shaded artifact POM and Jersey Client

### ISSUE THREAD

**Issue by stanicek** [oracle/oci-java-sdk#57]
Hi, 

do you plan to publish pom.xml of shaded artifact? We'd like to include Jersey-Client into shaded JAR  because of possible conflict with Weblogic's internal Jersey-Client 1.x.

Thanks.

**Comment by benthamc** [comment]
No, but we will consider your request. Thanks!

**Comment by benthamc** [comment]
You can find the pom.xml file here - 
https://github.com/oracle/oci-java-sdk/blob/master/bmc-shaded/pom.xml

Thanks!
