### ISSUE TITLE
Empty compartment id in audit events

### ISSUE THREAD

**Issue by dipeen-oracle** [oracle/oci-java-sdk#66]
Hi, we are getting null or no entry in some of the create events from Audit event's service.
can you please explain why?
Plus, What is the event source = CorePublicServiceAPI ? We are getting it in create VCN event log.

**Comment by pritams21** [comment]
Hi dipeen-oracle, can you provide more info on what the issue is? are you getting eventName as null?

**Comment by dipeen-oracle** [comment]
No, event name is not needed.
For
requestAction=GET
requestResource=/n/ORACLECASB/b?compartmentId=ocid1.compartment.oc1..................q56umtlueevnf7ba
Which kind of event is this ?

**Comment by jodoglevy** [comment]
@pritams21  can you please respond here?

**Comment by jodoglevy** [comment]
@pritams21  ping ^

**Comment by mricken** [comment]
@pritams21  Please respond. The customer has provided more information.

**Comment by jodoglevy** [comment]
@pritams21  - ping

**Comment by vaibhavumd** [comment]
This is createVcn event which is of type "om.oraclecloud.virtualNetwork.CreateVcn" and it comes from "virtualNetwork" as source and  "ORACLECASB" is the compartment. Is this what you are trying to get ? Do you need more information or something ?

**Comment by KartikShrikantHegde** [comment]
@dipeen-oracle Please let us know if you need help with this issue. If not, I will close the ticket and you can reopen if you still have the problem.

**Comment by KartikShrikantHegde** [comment]
@dipeen-oracle closing this ticket for now. Please re-open if you still have problems.
