### ISSUE TITLE
Need List subscribed compartment API

### ISSUE THREAD

**Issue by aunayak** [oracle/oci-java-sdk#67]
Hi ,
we have different compartments available in the OCI, and if we want to list events we have to set the compartmentID. listCompartments will list out all the compartments and if some compartment has policy restriction we get 404 error. So can we have and api to list the compartments for which user has access just like list subscribed region?

**Comment by zokun** [comment]
Hi aunayak, this is a tricky request. What specifically do you mean when you say "compartments for which the user has access"? Do you mean they have the COMPARTMENT_INSPECT permission? Or that they have just some level of permission in that compartment (e.g. launch instances)?

**Comment by MartinSleeman** [comment]
So aunayak, we have updated our APIs so that list compartments should only return those which you have access to.  If that's not the case, please let me know.

**Comment by aunayak** [comment]
Cool... thanks! may i know this is rolled out in which java version ?

**Comment by jodoglevy** [comment]
This was released in [version 1.3.0](https://github.com/oracle/oci-java-sdk/releases/tag/v1.3.0) - you can use the accessLevel parameter of the ListCompartments API to do this.
