### ISSUE TITLE
Using a non-default profile results in "java.lang.IllegalStateException: No DEFAULT profile was specified in the configuration"

### ISSUE THREAD

**Issue by abhirockzz** [oracle/oci-java-sdk#76]
I am trying to use a custom profile in the config file e.g.

```
[my-profile]
user=foo
fingerprint=bar
key_file=oci_api_key.pem
tenancy=foor
region=us-phoenix-1
pass_phrase=bar
```
Trying to parse it using

`ConfigFileReader.parse(in, "my-profile");` //`in` is an `InputStream`

But I end up getting `java.lang.IllegalStateException: No DEFAULT profile was specified in the configuration`

Is it not possible to use a non-default profile as the ONLY profile in the config ?

**Comment by priteshkp** [comment]
hey @abhirockzz .  The default profile is required even if you don't use it.  Think of it as the base profile that everything else inherits from.  If you have nothing to inherit, then just leave that part blank:
```
[DEFAULT]
# nothing to inherit

[my-profile]
user=foo
fingerprint=bar
key_file=oci_api_key.pem
tenancy=foor
region=us-phoenix-1
pass_phrase=bar
```

**Comment by sumitkdey** [comment]
Hey @abhirockzz, From release 1.2.48, you no longer need to specify the default profile if you don't need it.
