### ISSUE TITLE
Timeouts while connecting to Object Storage

### ISSUE THREAD

**Issue by SCBob** [oracle/oci-java-sdk#92]
I am getting timeouts when I try to use the ObjectStorageClient and ObjectStorageAsyncClient  clients.    I do not see timeouts for the other services - only ObjectStorage.    I see this problem is my code and in the examples ObjectStorageGetBucketExample and ObjectStorageAsyncExample.  

To be clear i have no problem using IdentityAsyncClient ComputeAsyncClient VirtualNetworkAsyncClient or DatabaseAsyncClient.  I can work with them with no issues so I do not think it is a network / proxy issue.  

The (partial) dump from ObjectStorageGetBucketExample 

 `SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Getting the namespace.
Exception in thread "main" com.oracle.bmc.model.BmcException: (-1, null, true) Timed out while communicating to: https://objectstorage.us-phoenix-1.oraclecloud.com (outbound opc-request-id: 4894BB1B5DB14613BD10C8AF25088AF3)
	at com.oracle.bmc.http.internal.RestClient.convertToBmcException(RestClient.java:539)
	at com.oracle.bmc.http.internal.RestClient.get(RestClient.java:101)
`

**Comment by sumitkdey** [comment]
Hello @SCBob,
Could you share the output of `curl -v https://objectstorage.us-phoenix-1.oraclecloud.com` from the same machine where the Java client is timing out. Another option worth trying is switching to a different region using the `setRegion` call on the client.

The Java SDK allows users to pass a configuration during client creation to control timeout values
https://github.com/oracle/oci-java-sdk/blob/b60d045abad0e68e20b50139516a879751dc33a2/bmc-objectstorage/bmc-objectstorage-generated/src/main/java/com/oracle/bmc/objectstorage/ObjectStorageClient.java#L43-L52
https://github.com/oracle/oci-java-sdk/blob/b60d045abad0e68e20b50139516a879751dc33a2/bmc-common/src/main/java/com/oracle/bmc/ClientConfiguration.java#L34-L44
You may try to update the timeout values and check if that helps.

**Comment by SCBob** [comment]
Thank you - the issue was the proxy.  It allowed all other access but blocked object storage.

**Comment by akhasaya** [comment]
@SCBob what proxy did you use to solve this issue?

**Comment by SCBob** [comment]
@akhasaya Are you an oracle employee?  I can message you internally on the proxy server that I used.  If you aren't that I can tell you how I found it.   I went in the browser settings and looked at the Proxy Settings there.  If you are lucky than it will be a straight forward url and port.  In our case we use a config file (which is listed in the settings)- which  contains a set of rules to use.   I choose on the the listed proxy servers in that file and used that to make it work.

Bob

If you are oracle and want to reach out via ARIA my last name is Marriott

**Comment by akhasaya** [comment]
Hi @SCBob  I am an Oracle Employee. My mail id is rajeswary.narasimman@oracle.com. Please ping me on slack or mail me. If you send me the proxy information, it will be very helpful.

**Comment by xiancao** [comment]
Hi @SCBob I got the same error when I tried to run sample ObjectStorageGetBucketExample.java. When I ran 'curl -v https://objectstorage.us-phoenix-1.oraclecloud.com', I got '404 Not Found'. I tried different proxy servers and all failed. Can you send me the proxy information to me too? I am an Oracle Employee and my email is xian.cao@oracle.com. Thanks!

**Comment by jodoglevy** [comment]
If you are trying to use the OCI Java SDK with a proxy, please see https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/javasdkconfig.htm#apache if you haven't already @akhasaya  @xiancao

**Comment by xiancao** [comment]
It works after using Apache Connector Add-On to configure http proxy server in the sample code. 
@jodoglevy thanks!

**Comment by akhasaya** [comment]
Changing the proxy worked for me. Thanks Bob. Thanks jodoglevy for sharing about apache connector too. I will try it out.
