### ISSUE TITLE
Include KMS key age/update time to calculate the kms key age

### ISSUE THREAD

**Issue by aunayak** [oracle/oci-java-sdk#94]
Currently to check the age of KMS key we have to do following things
1) List vaults -> list keys ->list key version-> get the last rotated key keyversion and calculate the number of days since its rotated

it id overburden and it would be better if keyage or last rotated date is available wen we list the keys instead of listing keys version and finding it out.

**Comment by KartikShrikantHegde** [comment]
Hi @aunayak , this seems to be an old issue, but did you try or can you try calculating it by calling GetKey, getting the active key version ocid from that, and call GetKeyVersion, and then getting the timeCreated from that? 

Please feel free to give this a try and let us know if you are still facing an issue. Thanks.

**Comment by KartikShrikantHegde** [comment]
Hi @aunayak , I am closing this ticket for now. Please give the above option a try and if you are still facing the issue, please feel free to re-open the ticket. Thanks.
